import 'dotenv/config';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { prisma } from '@/lib/prisma';
import { csv, experiment, parseCsv, sha256, verifyCorpus } from '@/experiments/hu04-multihorizon';

const root = resolve(import.meta.dir, '..', '..'); const evidence = resolve(root, 'docs/evidencias/hu-04-multihorizon'); const corpusDirectory = resolve(evidence, 'corpus');
mkdirSync(corpusDirectory, { recursive: true });
const source = await prisma.xmConsolidatedDataset.findFirst({ where: { metric: 'Gene' }, orderBy: [{ requestedTo: 'desc' }, { id: 'desc' }], select: { id: true, energyDatasetId: true, requestedFrom: true, requestedTo: true, contentHash: true, energyDataset: { select: { content: true } } } });
if (!source || !source.energyDataset || typeof source.energyDataset.content !== 'object' || source.energyDataset.content === null || !('records' in source.energyDataset.content) || !Array.isArray(source.energyDataset.content.records)) throw new Error('Latest Gene consolidated dataset is invalid.');
const records = source.energyDataset.content.records.map(record => {
  if (!record || typeof record !== 'object' || !('fecha_xm' in record) || !('hora_xm' in record) || !('energia_kwh' in record)) throw new Error('Invalid Gene record.');
  return { fecha_xm: String(record.fecha_xm), hora_xm: Number(record.hora_xm), energia_kwh: Number(record.energia_kwh) };
}).sort((left, right) => left.fecha_xm.localeCompare(right.fecha_xm) || left.hora_xm - right.hora_xm);
const contents = csv(records); const corpusPath = resolve(corpusDirectory, `xm-gene-${source.requestedFrom.toISOString().slice(0, 10)}_${source.requestedTo.toISOString().slice(0, 10)}.csv`); writeFileSync(corpusPath, contents, 'utf8');
const frozenContents = readFileSync(corpusPath, 'utf8'); const frozenRecords = parseCsv(frozenContents); const verified = verifyCorpus(frozenRecords); const corpusHash = sha256(frozenContents); const output = experiment(frozenRecords, corpusHash);
const manifest = { provider: 'XM/SINERGOX', source: { consolidatedDatasetId: source.id, energyDatasetId: source.energyDatasetId, contentHash: source.contentHash }, extractedAt: new Date().toISOString(), corpus: { file: corpusPath.slice(root.length + 1).replaceAll('\\', '/'), sha256: corpusHash, range: `${verified.firstDate}..${verified.lastDate}`, observations: verified.observations, completeDays: verified.completeDays, gaps: 0, duplicates: 0, incompleteDays: 0 } };
writeFileSync(resolve(corpusDirectory, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`, 'utf8'); writeFileSync(resolve(evidence, 'results.json'), `${JSON.stringify(output, null, 2)}\n`, 'utf8');
const holdoutRows = Object.values(output.results).map((result: any) => `| ${result.horizonDays} | ${result.modelId} | ${result.validation.selectedAlpha} | ${result.externalHoldout.ridge.MAE.toFixed(2)} | ${result.externalHoldout.ridge.RMSE.toFixed(2)} | ${result.externalHoldout.ridge.bias.toFixed(2)} | ${result.externalHoldout.ridge.WAPE.toFixed(4)} | ${result.validation.baselineReference} | ${result.candidate} |`).join('\n');
const validationRows = Object.values(output.results).map((result: any) => { const selected = result.validation.ridge.find((entry: any) => entry.alpha === result.validation.selectedAlpha); const baseline = result.validation.baselines[result.validation.baselineReference]; return `| ${result.horizonDays} | ${result.validation.selectedAlpha} | ${selected.metrics.MAE.toFixed(2)} | ${selected.metrics.RMSE.toFixed(2)} | ${selected.metrics.bias.toFixed(2)} | ${selected.metrics.WAPE.toFixed(4)} | ${result.validation.baselineReference} | ${baseline.MAE.toFixed(2)} |`; }).join('\n');
const sampleRows = Object.values(output.results).map((result: any) => `| ${result.horizonDays} | ${result.samples.train} | ${result.samples.validation} | ${result.samples.externalHoldout} |`).join('\n');
writeFileSync(resolve(evidence, 'README.md'), `# HU-04 — Experimento directo multi-horizonte D+1..D+7\n\nEste experimento offline usa siete Ridge directos independientes. Para cada origen calendario t, las features se limitan a t o antes; el target es energia_kwh(t+h, periodo). No se usa recursión ni predicciones como features. Los artefactos son experimentales y no los carga el runtime.\n\n## Corpus\n\nVer [manifest](corpus/manifest.json). El script extrae el consolidado Gene, congela CSV, vuelve a leerlo y solo entonces entrena/evalúa.\n\n## Definición\n\nPara cada periodo p: \`X(t,p)=[energia(t,p), energia(t-6,p), energia(t,24), sin, cos]\`; \`y(t,h,p)=energia(t+h,p)\`. Todas las fechas de features son <= t.\n\n## Particiones\n\nTargets TRAIN 2024-10-01..2026-03-31; VALIDATION 2026-04-01..2026-05-31; EXTERNAL HOLDOUT 2026-06-01..2026-09-20. El holdout no participa en selección.\n\n| h | TRAIN muestras | VALIDATION muestras | HOLDOUT muestras |\n|---:|---:|---:|---:|\n${sampleRows}\n\n## Regla de promoción\n\nPor horizonte: cero indisponibles, números finitos, MAE holdout <= 1.05x baseline seleccionado por VALIDATION, mejora estricta MAE o RMSE, WAPE <= 1.25x baseline y error absoluto máximo <= 10x desviación estándar de targets TRAIN.\n`, 'utf8');
writeFileSync(resolve(evidence, 'resultados.md'), `# Resultados\n\n## Selección en VALIDATION\n\n| h | alpha | MAE Ridge | RMSE Ridge | Bias Ridge | WAPE Ridge | baseline seleccionado | MAE baseline |\n|---:|---:|---:|---:|---:|---:|---|---:|\n${validationRows}\n\n## Evaluación EXTERNAL HOLDOUT\n\n| h | modelId | alpha | MAE | RMSE | Bias | WAPE | baseline | candidate |\n|---|---|---:|---:|---:|---:|---:|---|---|\n${holdoutRows}\n\nLas métricas completas de validation, baselines, diagnóstico por periodo y holdout están en [results.json](results.json).\n`, 'utf8');
writeFileSync(resolve(evidence, 'pruebas.md'), `# Pruebas\n\n` + `Ejecutar: \`bun test src/tests/hu04-multihorizon.test.ts\`.\n\n` + `Cubre continuidad del corpus, 24 periodos, ausencia de duplicados, muestras h1/h7, targetDate=origin+h, anti-leakage, scaler TRAIN, selección sin holdout, paridad del artefacto candidato y métricas finitas.\n`, 'utf8');
for (const result of Object.values(output.results) as any[]) if (result.candidate) { const modelPath = resolve(root, `backend/src/models/${result.modelId}/1.0.0/model.json`); mkdirSync(dirname(modelPath), { recursive: true }); const artifact = { modelId: result.modelId, modelVersion: '1.0.0-experimental', algorithm: 'ridge', hyperparameters: { alpha: result.validation.selectedAlpha }, horizonDays: result.horizonDays, forecastOriginDefinition: result.originDefinition, targetDefinition: result.targetDefinition, orderedFeatures: result.orderedFeatures, coefficients: result.artifact.coefficients, intercept: result.artifact.intercept, scaler: { ddof: 0, means: result.artifact.means, standardDeviations: result.artifact.standardDeviations }, trainingRange: result.ranges.train, validationRange: result.ranges.validation, externalHoldoutRange: result.ranges.externalHoldout, corpusHash: result.corpusHash, metrics: { validation: result.validation.ridge.find((entry: any) => entry.alpha === result.validation.selectedAlpha).metrics, externalHoldout: result.externalHoldout.ridge }, baselineReference: result.validation.baselineReference, promotionCriteria: { completeCoverage: true, finite: true, maeMultiplier: 1.05, wapeMultiplier: 1.25, catastrophicErrorMultiplierOfTrainTargetStandardDeviation: 10 }, limitations: ['Experimental offline artifact; not loaded by runtime.', 'Generation XM is a proxy for availability, not transactional supply.', 'No recursive forecasting or predicted features.', 'Academic/formal validation pending.'] }; writeFileSync(modelPath, `${JSON.stringify(artifact, null, 2)}\n`, 'utf8'); }
console.log(JSON.stringify({ manifest, candidates: Object.values(output.results).filter((result: any) => result.candidate).map((result: any) => result.modelId) }, null, 2));