import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { parseCsv, predict, samples, sha256, verifyCorpus } from '@/experiments/hu08-price-multihorizon';
import { baseFeaturesV2, experimentV2, omittedExactRedundanciesV2, orderedFeaturesV2, targetRelativeFeatures } from '@/experiments/hu08-price-multihorizon-v2';

const root = resolve(import.meta.dir, '..', '..'), v1Directory = resolve(root, 'docs/evidencias/hu-08-price-multihorizon-v1'), evidence = resolve(root, 'docs/evidencias/hu-08-price-multihorizon-v2');
const manifestV1 = JSON.parse(readFileSync(resolve(v1Directory, 'corpus/manifest.json'), 'utf8')) as any, resultsV1 = JSON.parse(readFileSync(resolve(v1Directory, 'results.json'), 'utf8')) as any;
const corpusPath = resolve(root, manifestV1.corpus.file), corpusText = readFileSync(corpusPath, 'utf8'), corpusHash = sha256(corpusText);
if (corpusHash !== '2aca8e5868eaff50909c8154a842bfbe8a8db873976a90145e73e02aa7c9b02e' || corpusHash !== manifestV1.corpus.sha256) throw new Error('HU-08 V1 corpus hash mismatch; V2 stopped.');
const records = parseCsv(corpusText), corpus = verifyCorpus(records); if (corpus.firstDate !== '2024-01-01' || corpus.lastDate !== '2026-09-28' || corpus.completeDays !== 1002 || corpus.observations !== 24048) throw new Error('HU-08 V1 corpus integrity mismatch; V2 stopped.');

const mean = (values: number[]) => values.reduce((total, value) => total + value, 0) / values.length;
function diagnostics(rows: ReturnType<typeof samples>, model: any) {
  const group = (key: (row: any) => string) => { const buckets = new Map<string, number[]>(); for (const row of rows) { const errors = buckets.get(key(row)) ?? []; errors.push(predict(model, row.features) - row.target); buckets.set(key(row), errors); } return Object.fromEntries([...buckets].map(([key, errors]) => [key, { evaluable: errors.length, MAE: mean(errors.map(Math.abs)), bias: mean(errors) }])); };
  const actual = rows.map(row => row.target), predicted = rows.map(row => predict(model, row.features));
  return { byPeriod: group(row => String(row.period)), byWeekday: group(row => String((new Date(`${row.targetDate}T00:00:00Z`).getUTCDay() + 6) % 7)), byMonth: group(row => row.targetDate.slice(0, 7)), distribution: { actual: { min: Math.min(...actual), max: Math.max(...actual), mean: mean(actual) }, predicted: { min: Math.min(...predicted), max: Math.max(...predicted), mean: mean(predicted) } } };
}
const v1Diagnostics: Record<string, unknown> = {};
for (let horizonDays = 1; horizonDays <= 7; horizonDays++) { const result = resultsV1.results[String(horizonDays)]; v1Diagnostics[String(horizonDays)] = { validation: diagnostics(samples(records, result.ranges.validation, horizonDays), result.fittedParameters), externalHoldoutPostHoc: diagnostics(samples(records, result.ranges.externalHoldout, horizonDays), result.fittedParameters) }; }

const output = experimentV2(records, corpusHash), comparison: Record<string, unknown> = {};
for (let horizonDays = 1; horizonDays <= 7; horizonDays++) { const key = String(horizonDays), v1 = resultsV1.results[key], v2 = output.results[key] as any; comparison[key] = { horizonDays, v1: { MAE: v1.externalHoldout.ridge.MAE, RMSE: v1.externalHoldout.ridge.RMSE, bias: v1.externalHoldout.ridge.bias, WAPE: v1.externalHoldout.ridge.WAPE, technicalCandidate: v1.technicalCandidate }, v2: { MAE: v2.externalHoldout.ridge.MAE, RMSE: v2.externalHoldout.ridge.RMSE, bias: v2.externalHoldout.ridge.bias, WAPE: v2.externalHoldout.ridge.WAPE, technicalCandidate: v2.technicalCandidate }, baseline: { id: v2.validation.baselineReference, metrics: v2.externalHoldout.baselines[v2.validation.baselineReference] } }; }
const results = { ...output, corpus: { ...output.corpus, file: manifestV1.corpus.file, sha256: corpusHash, source: manifestV1.source }, v1Diagnostics, comparisonV1V2: comparison };
mkdirSync(evidence, { recursive: true }); writeFileSync(resolve(evidence, 'results.json'), `${JSON.stringify(results, null, 2)}\n`, 'utf8'); writeFileSync(resolve(evidence, 'manifest.json'), `${JSON.stringify({ experimentId: output.experimentId, corpus: results.corpus, partitions: output.partitions, promotionCriteria: output.promotionCriteria, v1ResultsFile: 'docs/evidencias/hu-08-price-multihorizon-v1/results.json', generatedAt: new Date().toISOString() }, null, 2)}\n`, 'utf8');

const sampleRows = Object.values(output.results).map((result: any) => `| ${result.horizonDays} | ${result.samples.train} | ${result.samples.validation} | ${result.samples.externalHoldout} | ${result.validation.selectedAlpha} | ${result.validation.baselineReference} |`).join('\n');
const holdoutRows = Object.values(output.results).map((result: any) => { const m = result.externalHoldout.ridge, b = result.externalHoldout.baselines[result.validation.baselineReference]; return `| ${result.horizonDays} | ${m.MAE.toFixed(6)} | ${b.MAE.toFixed(6)} | ${m.RMSE.toFixed(6)} | ${m.bias.toFixed(6)} | ${m.WAPE.toFixed(6)} | ${m.maxAbsoluteError.toFixed(6)} | ${result.externalHoldout.catastrophicThreshold.toFixed(6)} | ${result.technicalCandidate} |`; }).join('\n');
const comparisonRows = Object.values(comparison).map((entry: any) => `| ${entry.horizonDays} | ${entry.v1.MAE.toFixed(6)} | ${entry.v2.MAE.toFixed(6)} | ${entry.baseline.id} (${entry.baseline.metrics.MAE.toFixed(6)}) | ${entry.v1.bias.toFixed(6)} | ${entry.v2.bias.toFixed(6)} | ${entry.v2.technicalCandidate} |`).join('\n');
const targetRelativeRows = Array.from({ length: 7 }, (_, index) => { const h = index + 1, features = targetRelativeFeatures(h); return `| ${h} | ${features.length ? features.map(item => `${item.name}=target-${item.targetLag}=origin-${item.originOffset}`).join('<br>') : 'Ninguna adicional; referencias target-relative duplican niveles origin-relative.'} |`; }).join('\n');

writeFileSync(resolve(evidence, 'README.md'), `# HU-08 — Precio directo multi-horizonte V2\n\n## Hipótesis fijada antes del holdout\n\nMayor memoria histórica, estadísticos robustos, calendario mensual y referencias semanales relativas al target pueden capturar persistencia/estacionalidad no representada por V1, especialmente h1-h3/h7. La decisión se justifica por estructura temporal conocida y diagnóstico TRAIN/VALIDATION; el holdout V1 se conserva solo como diagnóstico post hoc. No se usan Oferta, Demanda, clima ni variables futuras.\n\n## Corpus y protocolo congelados\n\nReutiliza exactamente \`${manifestV1.corpus.file}\`, SHA-256 \`${corpusHash}\`, ${corpus.firstDate}..${corpus.lastDate}, ${corpus.completeDays} días y ${corpus.observations} filas. Particiones, Ridge, grid 0.01/0.1/1/10/100, baselines y promoción son idénticos a V1. Alpha/baseline se seleccionan solo con VALIDATION.\n\n## Diagnóstico V1 previo\n\nEn VALIDATION, periodo 20 concentra el mayor MAE y bias negativo en todos los horizontes; martes concentra frecuentemente el bias negativo y mayo queda subestimado. El promedio predicho está entre 13 y 24 COP/kWh por debajo del real según horizonte. Post hoc en holdout, el sesgo negativo crece con h y se concentra especialmente en periodos 19–20, viernes/sábado y agosto. Estas observaciones documentan V1, pero no seleccionan features V2.\n\n## Features V2\n\n${baseFeaturesV2.map(feature => `- \`${feature}\``).join('\n')}\n\n### Eliminadas por redundancia exacta\n\n${Object.entries(omittedExactRedundanciesV2).map(([feature, reason]) => `- \`${feature}\`: ${reason}`).join('\n')}\n\n### Referencias target-relative no duplicadas\n\n| h | feature y fecha real |\n|---:|---|\n${targetRelativeRows}\n\nTodas cumplen target-lag <= origin. h1 y h7 no agregan referencias porque serían duplicados exactos de niveles origin-relative ya presentes.\n\n## Muestras y selección\n\n| h | TRAIN | VALIDATION | EXTERNAL HOLDOUT | alpha | baseline |\n|---:|---:|---:|---:|---:|---|\n${sampleRows}\n\n## Alcance\n\nLos artefactos son experimentales y no están conectados a runtime. \`technicalCandidate\` no equivale a validación académica, recomendación financiera ni liquidación.\n`, 'utf8');
writeFileSync(resolve(evidence, 'resultados.md'), `# Resultados HU-08 Precio V2\n\n## EXTERNAL HOLDOUT\n\n| h | MAE V2 | MAE baseline | RMSE | Bias | WAPE | max abs error | catastrophic threshold | technicalCandidate |\n|---:|---:|---:|---:|---:|---:|---:|---:|---|\n${holdoutRows}\n\n## Comparación V1/V2\n\n| h | V1 MAE | V2 MAE | baseline (MAE) | V1 bias | V2 bias | candidate V2 |\n|---:|---:|---:|---|---:|---:|---|\n${comparisonRows}\n\nMétricas completas por periodo y V2 por weekday, diagnóstico V1 por periodo/weekday/mes y distribuciones están en [results.json](results.json).\n`, 'utf8');
writeFileSync(resolve(evidence, 'pruebas.md'), '# Pruebas\n\nEjecutar `bun test src/tests/hu08-price-multihorizon-v2.test.ts`. Cubre hash, corpus, h1/h7, fechas target-relative, anti-leakage, redundancias, scaler TRAIN, selección VALIDATION, holdout aislado, paridad y artefactos candidate-only.\n', 'utf8');

for (const result of Object.values(output.results) as any[]) if (result.technicalCandidate) { const modelPath = resolve(root, `backend/src/models/${result.modelId}/1.0.0/model.json`); mkdirSync(dirname(modelPath), { recursive: true }); const artifact = { modelId: result.modelId, modelVersion: result.modelVersion, algorithm: 'ridge', experimentVersion: 'v2', hyperparameters: { alpha: result.validation.selectedAlpha }, horizonDays: result.horizonDays, forecastOriginDefinition: result.originDefinition, targetDefinition: result.targetDefinition, orderedFeatures: result.orderedFeatures, targetRelativeFeatures: result.targetRelativeFeatures, coefficients: result.fittedParameters.coefficients, intercept: result.fittedParameters.intercept, scaler: { ddof: 0, means: result.fittedParameters.means, standardDeviations: result.fittedParameters.standardDeviations }, trainingRange: result.ranges.train, validationRange: result.ranges.validation, externalHoldoutRange: result.ranges.externalHoldout, corpusHash, metrics: { validation: result.validation.ridge.find((entry: any) => entry.alpha === result.validation.selectedAlpha).metrics, externalHoldout: result.externalHoldout.ridge }, baseline: { selectedOn: 'validation', reference: result.validation.baselineReference, validation: result.validation.baselines[result.validation.baselineReference], externalHoldout: result.externalHoldout.baselines[result.validation.baselineReference] }, promotionCriteria: result.promotionCriteria, limitations: ['Experimental V2 artifact; not loaded by runtime.', 'Reference price only; not financial settlement or personalized recommendation.', 'No recursive forecasting or predicted/exogenous features.', 'Only historical PrecBolsNaci and calendar features.', 'Academic/formal validation pending.'] }; writeFileSync(modelPath, `${JSON.stringify(artifact, null, 2)}\n`, 'utf8'); }
console.log(JSON.stringify({ corpusHash, technicalCandidates: Object.values(output.results).filter((result: any) => result.technicalCandidate).map((result: any) => result.modelId) }, null, 2));