import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { parseCsv as parseAlignedCsv } from '@/experiments/hu08-price-multihorizon-v3';
import { adjustmentPartitions, csv, frozenPromotionCriteria, orderedFeaturesV4, parseCsv, preregisterModels, preregistrationVersion, prospectiveEvidenceMinimum, sha256, verifyCorpus, type PriceGeneRecord } from '@/experiments/hu08-price-v4-preregistration';

const root = resolve(import.meta.dir, '..', '..'), evidence = resolve(root, 'docs/evidencias/hu-08-price-v4-preregistration'), corpusDirectory = resolve(evidence, 'corpus'), modelsDirectory = resolve(evidence, 'frozen-models'); mkdirSync(corpusDirectory, { recursive: true }); mkdirSync(modelsDirectory, { recursive: true });
const v3Manifest = JSON.parse(readFileSync(resolve(root, 'docs/evidencias/hu-08-price-multihorizon-v3-exogenous/corpus/manifest.json'), 'utf8')) as any, alignedPath = resolve(root, v3Manifest.corpus.file), aligned = parseAlignedCsv(readFileSync(alignedPath, 'utf8'));
const adjustment: PriceGeneRecord[] = aligned.filter(row => row.fecha_xm <= adjustmentPartitions.validation.end).map(row => ({ fecha_xm: row.fecha_xm, periodo: row.periodo, precio_cop_kwh: row.precio_cop_kwh, generacion_kwh: row.generacion_kwh, generacion_total_diaria_kwh: row.generacion_total_diaria_kwh }));
const corpusFile = 'price-gene-adjustment-2024-01-01_2026-05-31.csv', corpusPath = resolve(corpusDirectory, corpusFile); writeFileSync(corpusPath, csv(adjustment), 'utf8'); const corpusText = readFileSync(corpusPath, 'utf8'), records = parseCsv(corpusText), verified = verifyCorpus(records), corpusHash = sha256(corpusText);
if (verified.firstDate !== '2024-01-01' || verified.lastDate !== '2026-05-31' || verified.days !== 882 || verified.observations !== 21168) throw new Error('V4 adjustment corpus integrity mismatch.');
const preregistrationCutoff = new Date().toISOString(), frozen = preregisterModels(records, corpusHash);
for (let horizonDays = 1; horizonDays <= 7; horizonDays++) writeFileSync(resolve(modelsDirectory, `h${horizonDays}.json`), `${JSON.stringify(frozen.results[String(horizonDays)], null, 2)}\n`, 'utf8');

const prospectiveEntrySchema = { generatedAt: 'ISO-8601 timestamp after preregistrationCutoff', forecastOriginDate: 'YYYY-MM-DD', targetDate: 'YYYY-MM-DD', horizonDays: '1..7', modelVersion: preregistrationVersion, prediction: '24 immutable period/value pairs', sourceCoverage: { priceUntil: 'YYYY-MM-DD', geneUntil: 'YYYY-MM-DD', priceFetchedAt: 'ISO-8601', geneFetchedAt: 'ISO-8601' }, featureSnapshotHash: 'SHA-256', previousEntryHash: 'SHA-256|null', entryHash: 'SHA-256' };
const sourceDatasets = { price: v3Manifest.corpus.sources.price, generation: v3Manifest.corpus.sources.generation, sourceAlignedSnapshot: { file: v3Manifest.corpus.file, sha256: v3Manifest.corpus.sha256 } };
const manifest = { preregistrationVersion, state: 'pendingProspectiveValidation', preregistrationCutoff, hypothesis: 'Observed Gene dynamics through forecastOriginDate improve future PrecBolsNaci beyond price-only V1.', family: 'Ridge direct h1..h7; Price V1 features plus frozen Gene-only features; no Demand or interactions.', adjustmentCorpus: { file: `docs/evidencias/hu-08-price-v4-preregistration/corpus/${corpusFile}`, sha256: corpusHash, range: { start: verified.firstDate, end: verified.lastDate }, days: verified.days, observations: verified.observations, periodsPerDay: 24, sourceDatasets }, partitions: adjustmentPartitions, forbiddenRetrospectiveBlock: { start: '2026-06-01', end: '2026-09-28', use: 'documentary evidence only; forbidden for V4 feature, alpha, baseline, criteria or horizon decisions' }, orderedFeatures: orderedFeaturesV4, alphaGrid: [0.01, 0.1, 1, 10, 100], baselines: ['B1_ORIGIN', 'B7', 'HISTORICAL_MEAN'], promotionCriteria: frozenPromotionCriteria, prospectiveEvidenceMinimum, prospectiveRegistry: { format: 'append-only JSONL with hash chain', schema: prospectiveEntrySchema, noEntriesAtPreregistration: true }, frozenModels: frozen.results };
writeFileSync(resolve(evidence, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');

const modelRows = Object.values(frozen.results).map(model => `| ${model.horizonDays} | ${model.selectedAlpha} | ${model.baselineReference} | ${model.validationMetrics.MAE.toFixed(6)} | ${model.baselineValidationMetrics.MAE.toFixed(6)} | ${model.state} |`).join('\n');
writeFileSync(resolve(evidence, 'README.md'), `# HU-08 Precio V4 Gene-only — Preregistración técnica\n\n## Estado\n\n\`pendingProspectiveValidation\`. No existen resultados prospectivos, candidatura técnica ni integración runtime. Cutoff: \`${preregistrationCutoff}\`.\n\n## Hipótesis congelada\n\nLa dinámica reciente de Gene observada hasta forecastOriginDate mejora PrecBolsNaci futuro frente a Precio V1. V4 excluye totalmente DemaSIN e interacciones Demanda/Generación. Cualquier feature nueva exige V5.\n\n## Features congeladas\n\n${orderedFeaturesV4.map(feature => `- \`${feature}\``).join('\n')}\n\nGene total diario es suma exacta de sus 24 periodos. Se conservan además Gene del mismo periodo p en t, t-1 y t-7. No hay forecasts futuros ni valores posteriores a t.\n\n## Ajuste permitido\n\nTRAIN ${adjustmentPartitions.train.start}..${adjustmentPartitions.train.end}; VALIDATION ${adjustmentPartitions.validation.start}..${adjustmentPartitions.validation.end}. Snapshot Price+Gene \`${corpusFile}\`, SHA-256 \`${corpusHash}\`. El bloque 2026-06-01..2026-09-28 está prohibido para decisiones V4 y solo permanece como evidencia V1/V2/V3.\n\n| h | alpha congelado | baseline congelado | MAE validation V4 | MAE baseline validation | estado |\n|---:|---:|---|---:|---:|---|\n${modelRows}\n\n## Evidencia prospectiva\n\nPreliminar: 14 target days completos por horizonte. Suficiente: mínimo 60 días completos/1.440 predicciones de periodo por horizonte, cubriendo al menos ocho ciclos semanales. Esto no garantiza potencia estadística universal; evita declarar suficiencia con uno o dos días. Solo targets XM recibidos después del cutoff pueden evaluarse.\n`, 'utf8');
writeFileSync(resolve(evidence, 'protocol.md'), `# Protocolo prospectivo HU-08 V4\n\n## Congelación\n\nVersión \`${preregistrationVersion}\`; cutoff \`${preregistrationCutoff}\`. Features, modelos, alpha, baseline, scaler y criterios de [manifest.json](manifest.json) no pueden cambiar sin crear V5.\n\n## Generación previa al target\n\nCuando Precio y Gene estén completos hasta t, generar D+1..D+7 usando solo fechas <=t. Cada día Gene debe contener 24 periodos. Si falta una fuente, registrar unavailable; no imputar. Guardar una entrada JSONL append-only con \`generatedAt\`, origen, target, horizonte, versión, 24 predicciones, cobertura fuente, hash de features, hash previo y hash de entrada. No existe API de actualización: una clave modelo/target/horizonte repetida se rechaza.\n\n## Evaluación\n\nEl target debe ser recibido por XM después de \`generatedAt\` y del cutoff. Comparar exclusivamente contra la predicción ya almacenada; nunca recalcularla con información posterior. Por horizonte reportar MAE, RMSE, Bias, WAPE, maxAbsoluteError, evaluable y unavailable.\n\n## Promoción congelada\n\nExigir mejora MAE >=1% y WAPE no peor frente al baseline congelado, unavailable=0 atribuible al modelo, finitud, maxAbsoluteError <= threshold TRAIN y ausencia de leakage. Para h4/h5/h6, donde V1 fue candidata, V4 debe además superar las predicciones prospectivas V1 generadas y congeladas en los mismos orígenes.\n\n## Suficiencia\n\n14 días completos: evidencia preliminar. 60 días completos por horizonte: evaluación prospectiva mínima suficiente para decisión técnica. Ambos estados deben informar indisponibles programados y no implican validación académica universal.\n`, 'utf8');
console.log(JSON.stringify({ preregistrationCutoff, adjustmentCorpusHash: corpusHash, state: frozen.state, models: Object.values(frozen.results).map(model => ({ h: model.horizonDays, alpha: model.selectedAlpha, baseline: model.baselineReference })) }, null, 2));