import 'dotenv/config';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { prisma } from '@/lib/prisma';
import { csv, experiment, parseCsv, sha256, verifyCorpus } from '@/experiments/hu08-price-multihorizon';

const root = resolve(import.meta.dir, '..', '..'), evidence = resolve(root, 'docs/evidencias/hu-08-price-multihorizon-v1'), corpusDirectory = resolve(evidence, 'corpus'); mkdirSync(corpusDirectory, { recursive: true });
const source = await prisma.xmConsolidatedDataset.findFirst({ where: { metric: 'PrecBolsNaci' }, orderBy: [{ requestedTo: 'desc' }, { id: 'desc' }], select: { id: true, energyDatasetId: true, requestedFrom: true, requestedTo: true, contentHash: true, sources: { select: { xmIngestionWindowId: true } }, energyDataset: { select: { status: true, validationReport: true, content: true } } } });
if (!source || source.energyDataset.status !== 'aprobado' || typeof source.energyDataset.content !== 'object' || source.energyDataset.content === null || !('records' in source.energyDataset.content) || !Array.isArray(source.energyDataset.content.records)) throw new Error('Latest approved PrecBolsNaci consolidated dataset is invalid.');
const records = source.energyDataset.content.records.map(record => { if (!record || typeof record !== 'object' || !('fecha_xm' in record) || !('periodo' in record) || !('precio_cop_kwh' in record)) throw new Error('Invalid PrecBolsNaci consolidated record.'); return { fecha_xm: String(record.fecha_xm), periodo: Number(record.periodo), precio_cop_kwh: Number(record.precio_cop_kwh) }; }).sort((left, right) => left.fecha_xm.localeCompare(right.fecha_xm) || left.periodo - right.periodo);
const corpusFile = `xm-preciobolsnaci-${source.requestedFrom.toISOString().slice(0, 10)}_${source.requestedTo.toISOString().slice(0, 10)}.csv`, corpusPath = resolve(corpusDirectory, corpusFile); writeFileSync(corpusPath, csv(records), 'utf8');
const sourceMetadata = { consolidatedDatasetId: source.id, energyDatasetId: source.energyDatasetId, contentHash: source.contentHash, sourceWindowIds: source.sources.map(item => item.xmIngestionWindowId).sort((left, right) => left - right), validationStatus: source.energyDataset.status, validationReport: source.energyDataset.validationReport };
await prisma.$disconnect();

const corpusText = readFileSync(corpusPath, 'utf8'), frozenRecords = parseCsv(corpusText), verified = verifyCorpus(frozenRecords), corpusHash = sha256(corpusText);
if (verified.firstDate !== '2024-01-01' || verified.lastDate !== '2026-09-28' || verified.completeDays !== 1002 || verified.observations !== 24048) throw new Error('Frozen PrecBolsNaci corpus integrity mismatch.');
const output = experiment(frozenRecords, corpusHash);
const manifest = { experimentId: output.experimentId, provider: 'XM/SINERGOX', source: sourceMetadata, extractedAt: new Date().toISOString(), corpus: { file: `docs/evidencias/hu-08-price-multihorizon-v1/corpus/${corpusFile}`, sha256: corpusHash, range: { start: verified.firstDate, end: verified.lastDate }, observations: verified.observations, completeDays: verified.completeDays, periodsPerDay: 24, unit: 'COP/kWh', gaps: verified.gaps, duplicates: verified.duplicates, missingValues: verified.missingValues, incompleteDays: verified.incompleteDays } };
writeFileSync(resolve(corpusDirectory, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`, 'utf8'); writeFileSync(resolve(evidence, 'results.json'), `${JSON.stringify({ ...output, corpus: { ...output.corpus, ...manifest.corpus }, source: sourceMetadata }, null, 2)}\n`, 'utf8');

const sampleRows = Object.values(output.results).map((result: any) => `| ${result.horizonDays} | ${result.samples.train} | ${result.samples.validation} | ${result.samples.externalHoldout} |`).join('\n');
const validationRows = Object.values(output.results).map((result: any) => { const ridge = result.validation.ridge.find((entry: any) => entry.alpha === result.validation.selectedAlpha).metrics, baseline = result.validation.baselines[result.validation.baselineReference]; return `| ${result.horizonDays} | ${result.validation.selectedAlpha} | ${result.validation.baselineReference} | ${ridge.MAE.toFixed(6)} | ${baseline.MAE.toFixed(6)} | ${ridge.RMSE.toFixed(6)} | ${ridge.bias.toFixed(6)} | ${ridge.WAPE.toFixed(6)} |`; }).join('\n');
const holdoutRows = Object.values(output.results).map((result: any) => { const metrics = result.externalHoldout.ridge, baseline = result.externalHoldout.baselines[result.validation.baselineReference]; return `| ${result.horizonDays} | ${result.validation.selectedAlpha} | ${result.validation.baselineReference} | ${metrics.MAE.toFixed(6)} | ${baseline.MAE.toFixed(6)} | ${metrics.RMSE.toFixed(6)} | ${metrics.bias.toFixed(6)} | ${metrics.WAPE.toFixed(6)} | ${metrics.maxAbsoluteError.toFixed(6)} | ${result.externalHoldout.catastrophicThreshold.toFixed(6)} | ${result.technicalCandidate} |`; }).join('\n');

writeFileSync(resolve(evidence, 'README.md'), `# HU-08 — Experimento directo multi-horizonte de precio V1\n\n## Alcance\n\nSiete Ridge directos independientes predicen 24 precios COP/kWh para targetDate=t+h, h=1..7. No hay recursión, predicciones previas, Oferta, Demanda ni variables futuras. B1 permanece baseline y runtime no cambia.\n\n## Corpus\n\nSnapshot congelado después de leer PostgreSQL: \`${manifest.corpus.file}\`, SHA-256 \`${corpusHash}\`, ${verified.firstDate}..${verified.lastDate}, ${verified.completeDays} días, ${verified.observations} filas, 24 periodos/día, sin huecos, duplicados, faltantes, no finitos ni días incompletos. Fuente: XmConsolidatedDataset ${source.id}, EnergyDataset ${source.energyDatasetId}.\n\n## Features\n\n${output.orderedFeatures.map(feature => `- \`${feature}\``).join('\n')}\n\nSe omitió \`mean_3d\` porque es combinación lineal exacta de t, t-1 y t-2 ya presentes. Rolling y estadísticos terminan en t.\n\n## Particiones fijadas antes de evaluar\n\n- TRAIN ${output.partitions.train.start}..${output.partitions.train.end}\n- VALIDATION ${output.partitions.validation.start}..${output.partitions.validation.end}\n- EXTERNAL HOLDOUT ${output.partitions.externalHoldout.start}..${output.partitions.externalHoldout.end}\n\nEl holdout es completamente posterior al holdout HU-08 documentado 2024-07-31..2024-09-28. No existe evidencia local de que el bloque 2026 se hubiera usado previamente para selección/evaluación de precio; esa trazabilidad no acredita por sí sola validación académica universal.\n\n| h | TRAIN | VALIDATION | EXTERNAL HOLDOUT |\n|---:|---:|---:|---:|\n${sampleRows}\n\n## Selección y promoción\n\nGrid alpha fijo: 0.01, 0.1, 1, 10, 100. Alpha y baseline se eligen solo con VALIDATION. Baselines: B1_ORIGIN=price(t,p), B7=price(target-7,p), HISTORICAL_MEAN por periodo ajustada solo en TRAIN. Promoción predefinida: unavailable=0, finitud, mejora MAE >=1%, WAPE no peor que baseline y maxAbsoluteError <=10 desviaciones estándar de targets TRAIN. No se relaja tras holdout.\n`, 'utf8');
writeFileSync(resolve(evidence, 'resultados.md'), `# Resultados HU-08 Precio D+1..D+7\n\n## VALIDATION\n\n| h | alpha | baseline | MAE Ridge | MAE baseline | RMSE | Bias | WAPE |\n|---:|---:|---|---:|---:|---:|---:|---:|\n${validationRows}\n\n## EXTERNAL HOLDOUT\n\n| h | alpha | baseline | MAE Ridge | MAE baseline | RMSE | Bias | WAPE | max abs error | catastrophic threshold | technicalCandidate |\n|---:|---:|---|---:|---:|---:|---:|---:|---:|---:|---|\n${holdoutRows}\n\nMétricas completas y diagnóstico por periodo 1..24: [results.json](results.json). \`technicalCandidate\` no equivale a validación académica, recomendación financiera ni integración runtime.\n`, 'utf8');
writeFileSync(resolve(evidence, 'pruebas.md'), '# Pruebas\n\nEjecutar `bun test src/tests/hu08-price-multihorizon.test.ts`. Cubre hash/corpus, 24 periodos, h1/h7, anti-leakage, B7, scaler TRAIN, selección VALIDATION, holdout aislado, métricas/per-periodo, paridad y artefactos solo candidate=true.\n', 'utf8');

for (const result of Object.values(output.results) as any[]) if (result.technicalCandidate) {
  const modelPath = resolve(root, `backend/src/models/${result.modelId}/1.0.0/model.json`); mkdirSync(dirname(modelPath), { recursive: true });
  const artifact = { modelId: result.modelId, modelVersion: result.modelVersion, algorithm: 'ridge', experimentVersion: 'v1', hyperparameters: { alpha: result.validation.selectedAlpha }, horizonDays: result.horizonDays, forecastOriginDefinition: result.originDefinition, targetDefinition: result.targetDefinition, orderedFeatures: result.orderedFeatures, coefficients: result.fittedParameters.coefficients, intercept: result.fittedParameters.intercept, scaler: { ddof: 0, means: result.fittedParameters.means, standardDeviations: result.fittedParameters.standardDeviations }, trainingRange: result.ranges.train, validationRange: result.ranges.validation, externalHoldoutRange: result.ranges.externalHoldout, corpusHash, metrics: { validation: result.validation.ridge.find((entry: any) => entry.alpha === result.validation.selectedAlpha).metrics, externalHoldout: result.externalHoldout.ridge }, baseline: { selectedOn: 'validation', reference: result.validation.baselineReference, validation: result.validation.baselines[result.validation.baselineReference], externalHoldout: result.externalHoldout.baselines[result.validation.baselineReference] }, promotionCriteria: result.promotionCriteria, limitations: ['Experimental offline artifact; not loaded by runtime.', 'Reference price only; not financial settlement or personalized recommendation.', 'No recursive forecasting or predicted features.', 'Only historical PrecBolsNaci and calendar features.', 'Academic/formal validation pending.'] };
  writeFileSync(modelPath, `${JSON.stringify(artifact, null, 2)}\n`, 'utf8');
}
console.log(JSON.stringify({ corpusHash, source: sourceMetadata, technicalCandidates: Object.values(output.results).filter((result: any) => result.technicalCandidate).map((result: any) => result.modelId) }, null, 2));