import 'dotenv/config';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { prisma } from '@/lib/prisma';
import { evaluateDemandObservationEligibility } from '@/services/demand-semantic-eligibility';
import { csv, experimentV3, parseCsv, verifyAlignedCorpus, type AlignedRecord } from '@/experiments/hu08-price-multihorizon-v3';

const root = resolve(import.meta.dir, '..', '..'), evidence = resolve(root, 'docs/evidencias/hu-08-price-multihorizon-v3-exogenous'), corpusDirectory = resolve(evidence, 'corpus'); mkdirSync(corpusDirectory, { recursive: true });
async function source(metric: string) { return prisma.xmConsolidatedDataset.findFirst({ where: { metric }, orderBy: [{ requestedTo: 'desc' }, { id: 'desc' }], select: { id: true, energyDatasetId: true, contentHash: true, requestedFrom: true, requestedTo: true, sources: { select: { xmIngestionWindowId: true } }, energyDataset: { select: { status: true, content: true } } } }); }
const [priceSource, geneSource, demandSource] = await Promise.all([source('PrecBolsNaci'), source('Gene'), source('DemaSIN')]);
for (const item of [priceSource, geneSource, demandSource]) if (!item || item.energyDataset.status !== 'aprobado' || typeof item.energyDataset.content !== 'object' || item.energyDataset.content === null || !('records' in item.energyDataset.content) || !Array.isArray(item.energyDataset.content.records)) throw new Error('Invalid aligned source dataset.');
const priceRecords = (priceSource!.energyDataset.content as any).records as any[], geneRecords = (geneSource!.energyDataset.content as any).records as any[], demandRecords = (demandSource!.energyDataset.content as any).records as any[];
const demandEligibility = new Map(evaluateDemandObservationEligibility(demandRecords.slice().sort((left, right) => left.fecha_xm.localeCompare(right.fecha_xm)).map(record => ({ date: String(record.fecha_xm), value: Number(record.demanda_kwh) }))).map(item => [item.date, item]));
const geneByKey = new Map(geneRecords.map(record => [`${record.fecha_xm}|${record.hora_xm}`, Number(record.energia_kwh)])), geneTotals = new Map<string, number>(); for (const record of geneRecords) geneTotals.set(record.fecha_xm, (geneTotals.get(record.fecha_xm) ?? 0) + Number(record.energia_kwh));
const demandByDate = new Map(demandRecords.map(record => [String(record.fecha_xm), Number(record.demanda_kwh)]));
const commonStart = '2024-01-01', commonEnd = '2026-09-28', aligned: AlignedRecord[] = [];
for (const record of priceRecords.slice().sort((left, right) => left.fecha_xm.localeCompare(right.fecha_xm) || left.periodo - right.periodo)) { if (record.fecha_xm < commonStart || record.fecha_xm > commonEnd) continue; const generation = geneByKey.get(`${record.fecha_xm}|${record.periodo}`), generationTotal = geneTotals.get(record.fecha_xm), demand = demandByDate.get(record.fecha_xm), eligibility = demandEligibility.get(record.fecha_xm); if (generation === undefined || generationTotal === undefined || demand === undefined || !eligibility) throw new Error(`Missing aligned source for ${record.fecha_xm}.`); aligned.push({ fecha_xm: record.fecha_xm, periodo: Number(record.periodo), precio_cop_kwh: Number(record.precio_cop_kwh), generacion_kwh: generation, generacion_total_diaria_kwh: generationTotal, demanda_kwh: demand, demand_semantic_status: eligibility.semanticStatus }); }
const corpusFile = `xm-price-gene-demand-${commonStart}_${commonEnd}.csv`, corpusPath = resolve(corpusDirectory, corpusFile); writeFileSync(corpusPath, csv(aligned), 'utf8');
const metadata = { price: { metric: 'PrecBolsNaci', consolidatedDatasetId: priceSource!.id, energyDatasetId: priceSource!.energyDatasetId, contentHash: priceSource!.contentHash }, generation: { metric: 'Gene', consolidatedDatasetId: geneSource!.id, energyDatasetId: geneSource!.energyDatasetId, contentHash: geneSource!.contentHash, aggregation: 'daily total = sum of exact 24 energia_kwh periods; same-period values retained' }, demand: { metric: 'DemaSIN', consolidatedDatasetId: demandSource!.id, energyDatasetId: demandSource!.energyDatasetId, contentHash: demandSource!.contentHash, semanticRule: 'demandasin_severe_drop_vs_trailing_median_v1', allExcludedDates: [...demandEligibility.values()].filter(item => item.semanticStatus === 'SEMANTIC_REVIEW_REQUIRED').map(item => item.date) } };
await prisma.$disconnect();

const corpusText = readFileSync(corpusPath, 'utf8'), frozen = parseCsv(corpusText), verified = verifyAlignedCorpus(frozen), corpusHash = createHash('sha256').update(corpusText).digest('hex'); if (verified.firstDate !== commonStart || verified.lastDate !== commonEnd || verified.completeDays !== 1002 || verified.observations !== 24048) throw new Error('Aligned V3 corpus integrity mismatch.');
const output = experimentV3(frozen, corpusHash), v1 = JSON.parse(readFileSync(resolve(root, 'docs/evidencias/hu-08-price-multihorizon-v1/results.json'), 'utf8')), v2 = JSON.parse(readFileSync(resolve(root, 'docs/evidencias/hu-08-price-multihorizon-v2/results.json'), 'utf8'));
const comparison: Record<string, unknown> = {}; for (let h = 1; h <= 7; h++) { const key = String(h), result = output.results[key] as any, combined = result.ablations.D_PRICE_DEMAND_GENERATION.externalHoldout.ridge; comparison[key] = { horizonDays: h, baseline: result.baselines.externalHoldout[result.baselineReference], v1: v1.results[key].externalHoldout.ridge, v2: v2.results[key].externalHoldout.ridge, v3: combined, v1Candidate: v1.results[key].technicalCandidate, v2Candidate: v2.results[key].technicalCandidate, v3TechnicalCandidate: result.technicalCandidate, replaceV1: result.technicalCandidate && (!v1.results[key].technicalCandidate || combined.MAE < v1.results[key].externalHoldout.ridge.MAE) }; }
const results = { ...output, corpus: { ...output.corpus, file: `docs/evidencias/hu-08-price-multihorizon-v3-exogenous/corpus/${corpusFile}`, sha256: corpusHash, sources: metadata }, comparisonV1V2V3: comparison };
writeFileSync(resolve(corpusDirectory, 'manifest.json'), `${JSON.stringify({ experimentId: output.experimentId, corpus: results.corpus, partitions: output.partitions, promotionCriteria: output.promotionCriteria, generatedAt: new Date().toISOString() }, null, 2)}\n`, 'utf8'); writeFileSync(resolve(evidence, 'results.json'), `${JSON.stringify(results, null, 2)}\n`, 'utf8');

const samplesRows = Object.values(output.results).map((result: any) => `| ${result.horizonDays} | ${result.samples.train} | ${result.samples.validation} | ${result.samples.externalHoldout} | ${result.losses.externalHoldout.priceHistory} | ${result.losses.externalHoldout.geneMissing} | ${result.losses.externalHoldout.demandMissing} | ${result.losses.externalHoldout.demandSemanticDirect} | ${result.losses.externalHoldout.demandSemanticRolling} |`).join('\n');
const ablationRows = Object.values(output.results).flatMap((result: any) => Object.entries(result.ablations).map(([name, value]: [string, any]) => `| ${result.horizonDays} | ${name} | ${value.validation.selectedAlpha} | ${value.externalHoldout.ridge.MAE.toFixed(6)} | ${value.externalHoldout.ridge.RMSE.toFixed(6)} | ${value.externalHoldout.ridge.bias.toFixed(6)} | ${value.externalHoldout.ridge.WAPE.toFixed(6)} | ${value.passesPromotionCriteria} |`)).join('\n');
const comparisonRows = Object.values(comparison).map((entry: any) => `| ${entry.horizonDays} | ${entry.baseline.MAE.toFixed(6)} | ${entry.v1.MAE.toFixed(6)} | ${entry.v2.MAE.toFixed(6)} | ${entry.v3.MAE.toFixed(6)} | ${entry.v1.bias.toFixed(6)} | ${entry.v3.bias.toFixed(6)} | ${entry.v3TechnicalCandidate} | ${entry.replaceV1} |`).join('\n');

writeFileSync(resolve(evidence, 'README.md'), `# HU-08 — Precio multi-horizonte V3 con exógenas observadas\n\n## Hipótesis\n\n¿La dinámica reciente de generación y demanda observadas hasta forecastOriginDate mejora Precio D+1..D+7 más allá de la historia propia de Precio? No se usan forecasts de Oferta/Demanda, valores futuros, clima ni variables comerciales futuras.\n\n## Snapshot alineado\n\nCSV \`docs/evidencias/hu-08-price-multihorizon-v3-exogenous/corpus/${corpusFile}\`, SHA-256 \`${corpusHash}\`, rango común ${verified.firstDate}..${verified.lastDate}, ${verified.completeDays} días y ${verified.observations} filas. Precio y Gene tienen 24 periodos exactos/día. Generación total diaria es la suma documentada de esos 24 periodos; también se retiene Gene del mismo periodo. DemaSIN conserva todas las filas y su estado semántico. Exclusiones globales: ${metadata.demand.allExcludedDates.join(', ')}; 29/09 queda fuera del rango común, 16/09 y 28/09 permanecen en CSV pero invalidan muestras que las atraviesan.\n\n## Fuentes\n\n- Precio: consolidado ${metadata.price.consolidatedDatasetId}, EnergyDataset ${metadata.price.energyDatasetId}.\n- Gene: consolidado ${metadata.generation.consolidatedDatasetId}, EnergyDataset ${metadata.generation.energyDatasetId}.\n- DemaSIN: consolidado ${metadata.demand.consolidatedDatasetId}, EnergyDataset ${metadata.demand.energyDatasetId}.\n\n## Features exógenas\n\nDemanda: ${output.demandFeatures.join(', ')}.\n\nGeneración: ${output.generationFeatures.join(', ')}.\n\nInteracción incluida: ratio demanda/generación total, válido como proxy agregado SIN porque ambas magnitudes están en kWh. Se omite demanda-generación por redundancia lineal exacta. Cambios diarios se conservan por protocolo solicitado aunque sean combinaciones de niveles Ridge. Todas las fechas y rolling windows terminan en t; cualquier DemaSIN en revisión invalida la muestra.\n\n## Muestras y pérdidas en holdout\n\n| h | TRAIN | VALIDATION | HOLDOUT | price history | Gene missing | Demand missing | semantic direct | semantic rolling |\n|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n${samplesRows}\n\n## Ablaciones\n\nA=Price V1; B=Price+Demand; C=Price+Generation; D=Price+Demand+Generation+ratio. Las cuatro usan exactamente las mismas muestras por horizonte. Alpha se selecciona solo con VALIDATION.\n\nLos artefactos combinados V3 permanecen offline y no se conectan a runtime.\n`, 'utf8');
writeFileSync(resolve(evidence, 'resultados.md'), `# Resultados HU-08 V3 exógeno\n\n## Ablation A/B/C/D\n\n| h | ablation | alpha | MAE | RMSE | Bias | WAPE | passesPromotionCriteria |\n|---:|---|---:|---:|---:|---:|---:|---|\n${ablationRows}\n\nLa ablación primaria V3 fue fijada como D antes del holdout. Los pases de A/B/C son diagnósticos de contribución y no candidatos seleccionables post hoc.\n\n## Comparación baseline/V1/V2/V3 combinado\n\n| h | baseline MAE | V1 MAE | V2 MAE | V3 MAE | V1 bias | V3 bias | candidate V3 | replace V1 |\n|---:|---:|---:|---:|---:|---:|---:|---|---|\n${comparisonRows}\n\nMétricas completas, pérdidas por partición, parámetros y criterios: [results.json](results.json). \`technicalCandidate\` no equivale a validación académica. Si V3 pasa baseline pero es peor que un V1 candidato, \`replaceV1=false\`.\n`, 'utf8');
writeFileSync(resolve(evidence, 'pruebas.md'), '# Pruebas\n\nEjecutar `bun test src/tests/hu08-price-multihorizon-v3.test.ts`. Cubre fuentes/hash, 24 periodos, alineación, leakage Gene/Demand, rolling, exclusiones semánticas, scaler TRAIN, selección VALIDATION, ablación, paridad y artefactos candidate-only.\n', 'utf8');

for (const result of Object.values(output.results) as any[]) if (result.technicalCandidate) { const combined = result.ablations.D_PRICE_DEMAND_GENERATION, modelPath = resolve(root, `backend/src/models/${result.modelId}/1.0.0/model.json`); mkdirSync(dirname(modelPath), { recursive: true }); const artifact = { modelId: result.modelId, modelVersion: result.modelVersion, algorithm: 'ridge', experimentVersion: 'v3-exogenous', hyperparameters: { alpha: combined.validation.selectedAlpha }, horizonDays: result.horizonDays, forecastOriginDefinition: result.originDefinition, targetDefinition: result.targetDefinition, features: result.features, coefficients: combined.fittedParameters.coefficients, intercept: combined.fittedParameters.intercept, scaler: { ddof: 0, means: combined.fittedParameters.means, standardDeviations: combined.fittedParameters.standardDeviations }, trainingRange: result.ranges.train, validationRange: result.ranges.validation, externalHoldoutRange: result.ranges.externalHoldout, corpusHash, sourceDatasets: metadata, metrics: { validation: combined.validation.ridge.find((entry: any) => entry.alpha === combined.validation.selectedAlpha).metrics, externalHoldout: combined.externalHoldout.ridge }, baseline: { selectedOn: 'validation', reference: result.baselineReference, validation: result.baselines.validation[result.baselineReference], externalHoldout: result.baselines.externalHoldout[result.baselineReference] }, promotionCriteria: result.promotionCriteria, limitations: ['Experimental V3 artifact; not loaded by runtime.', 'Uses observed Price, Gene and semantically eligible DemaSIN only through origin.', 'No future forecasts, weather or commercial variables.', 'Reference price only; not settlement or personalized recommendation.', 'Academic/formal validation pending.'] }; writeFileSync(modelPath, `${JSON.stringify(artifact, null, 2)}\n`, 'utf8'); }
console.log(JSON.stringify({ corpusHash, commonRange: { start: verified.firstDate, end: verified.lastDate }, sources: metadata, technicalCandidates: Object.values(output.results).filter((result: any) => result.technicalCandidate).map((result: any) => result.modelId) }, null, 2));