import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {strict as assert} from 'node:assert';
import { configureIsolatedIntegrationDatabase } from './integration-safety';
configureIsolatedIntegrationDatabase();
const { createApp } = await import('../src/app');
const { prisma } = await import('../src/lib/prisma');
const { authCookieName } = await import('../src/services/auth.service');
const { publicationWindow } = await import('../src/services/hourly-publication.contract');
const users:string[]=[];const runId=randomBytes(8).toString('hex');const results:string[]=[];
const app = createApp({ expirationScope: { userIds: users } });
const server=app.listen(0);const address=server.address();if(!address||typeof address==='string')throw new Error('No port');const base=`http://127.0.0.1:${address.port}`;
let phase='fixture publication and verification';
async function actor(){const user=await prisma.user.create({data:{email:`payment-${runId}-${users.length}@example.test`,name:'Payment fixture',passwordHash:'disabled-integration-fixture'}});users.push(user.id);const token=randomBytes(32).toString('base64url');await prisma.authSession.create({data:{userId:user.id,tokenHash:createHash('sha256').update(token).digest('hex'),expiresAt:new Date(Date.now()+3600000)}});return{id:user.id,cookie:`${authCookieName}=${token}`};}
async function request(cookie:string,path:string,body?:unknown){const response=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{Cookie:cookie,...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:response.status,data:await response.json() as any};}
function pass(id:string){results.push(id);console.log(JSON.stringify({id,status:'passed'}));}
try{
 const seller=await actor(),buyer=await actor(),other=await actor();const deliveryDate=publicationWindow().dates[0]!;const dateValue=new Date(`${deliveryDate}T00:00:00.000Z`);const hours=[8,9,10,11];
 for(const [owner,kind] of [[seller,'offer'],[buyer,'demand']] as const){phase=`${kind} hourly publication`;const published=await request(owner.cookie,'/publications',{kind,days:[{deliveryDate,hours:hours.map(hour=>({hour,quantityKwh:10.25,pricePerKwh:kind==='offer'?980.12345:1000}))}]});assert.equal(published.status,201);}
 for(const [owner,kind] of [[seller,'offer'],[buyer,'demand']] as const){phase=`${kind} capacity profile`;const profile=await request(owner.cookie,'/publication-verifications/profiles',{kind,limits:hours.map(hour=>({hour,maxQuantityKwh:'10.25'}))});assert.equal(profile.status,201);const rows=kind==='offer'?await prisma.energyOffer.findMany({where:{userId:owner.id,deliveryDate:dateValue}}):await prisma.energyDemand.findMany({where:{userId:owner.id,deliveryDate:dateValue}});assert.equal(rows.length,hours.length);for(const row of rows){phase=`${kind} approval for hourly publication`;const verified=await request(owner.cookie,`/publication-verifications/${kind}/${row.id}`,{});assert.equal(verified.data.verification.status,'APPROVED');}}
 const offers=new Map((await prisma.energyOffer.findMany({where:{userId:seller.id,deliveryDate:dateValue}})).map(row=>[row.hour,row]));const demands=new Map((await prisma.energyDemand.findMany({where:{userId:buyer.id,deliveryDate:dateValue}})).map(row=>[row.hour,row]));
 async function agreement(hour:number,confirm=true){const offer=offers.get(hour),demand=demands.get(hour);assert(offer&&demand);const proposed=await request(buyer.cookie,'/transactions',{offerId:offer.id,demandId:demand.id,quantityKwh:10.25,pricePerKwh:980.12345});assert.equal(proposed.status,201);if(!confirm)return proposed.data.transaction;const accepted=await request(seller.cookie,`/transactions/${proposed.data.transaction.id}/accept`,{});assert.equal(accepted.status,200);assert.equal(accepted.data.transaction.status,'CONFIRMED');return accepted.data.transaction;}
 phase='negotiation and initial payment authorization';
 const transaction=await agreement(8);const input=(scenario:string,key=randomUUID(),id=transaction.id)=>({transactionId:id,scenario,requestKey:key});
 assert.equal((await request('','/simulated-payments',input('APPROVED'))).status,401);assert.equal((await request(seller.cookie,'/simulated-payments',input('APPROVED'))).status,403);assert.equal((await request(other.cookie,`/simulated-payments/transactions/${transaction.id}`)).status,404);pass('PAY-INT-01');
 const pendingAgreement=await agreement(9,false);assert.equal((await request('','/simulated-payments/payables')).status,401);assert.deepEqual((await request(buyer.cookie,'/simulated-payments/payables')).data,{unpaidCount:1,pendingCount:0,totalCount:1,simulated:true});assert.equal((await request(seller.cookie,'/simulated-payments/payables')).data.totalCount,0);assert.equal((await request(other.cookie,'/simulated-payments/payables')).data.totalCount,0);pass('PAY-NOTICE-INT-01');assert.equal((await request(buyer.cookie,'/transactions/mine')).data.transactions.find((row:any)=>row.id===transaction.id).paymentStatus,'UNPAID');assert.equal((await request(buyer.cookie,'/simulated-payments',input('APPROVED',randomUUID(),pendingAgreement.id))).status,409);pass('PAY-INT-02');
 assert.equal((await request(buyer.cookie,'/simulated-payments',{...input('APPROVED'),amountCop:'1'})).status,400);pass('PAY-INT-03');
 assert.equal((await request(buyer.cookie,'/simulated-payments',input('REJECTED'))).data.attempt.status,'REJECTED');const pending=await request(buyer.cookie,'/simulated-payments',input('PENDING'));assert.equal(pending.status,201);assert.equal((await request(buyer.cookie,'/simulated-payments',input('APPROVED'))).status,409);pass('PAY-INT-04');assert.deepEqual((await request(buyer.cookie,'/simulated-payments/payables')).data,{unpaidCount:0,pendingCount:1,totalCount:1,simulated:true});pass('PAY-NOTICE-INT-02');assert.equal((await request(buyer.cookie,'/transactions/mine')).data.transactions.find((row:any)=>row.id===transaction.id).paymentStatus,'PENDING');
 const approved=await request(buyer.cookie,`/simulated-payments/${pending.data.attempt.id}/resolve`,{outcome:'APPROVED'});assert.equal(approved.status,200);assert.equal(approved.data.attempt.amountCop,'10046.2653625');assert(approved.data.attempt.receiptReference.startsWith('SIM-'));pass('PAY-INT-05');assert.equal((await request(buyer.cookie,'/simulated-payments/payables')).data.totalCount,0);pass('PAY-NOTICE-INT-03');assert.equal((await request(buyer.cookie,'/transactions/mine')).data.transactions.find((row:any)=>row.id===transaction.id).paymentStatus,'PAID');
 const replay=await request(buyer.cookie,`/simulated-payments/${pending.data.attempt.id}/resolve`,{outcome:'APPROVED'});assert.equal(replay.data.attempt.receiptReference,approved.data.attempt.receiptReference);assert.equal((await request(buyer.cookie,`/simulated-payments/${pending.data.attempt.id}/resolve`,{outcome:'REJECTED'})).status,409);assert.equal((await request(buyer.cookie,'/simulated-payments',input('APPROVED'))).status,409);pass('PAY-INT-06');
 const history=await request(seller.cookie,`/simulated-payments/transactions/${transaction.id}`);assert.equal(history.data.status,'PAID');assert.equal(history.data.attempts.length,2);assert.equal((await prisma.energyTransaction.findUniqueOrThrow({where:{id:transaction.id}})).status,'CONFIRMED');pass('PAY-INT-07');
 const replayAgreement=await agreement(10);const body=input('REJECTED',randomUUID(),replayAgreement.id);const original=await request(buyer.cookie,'/simulated-payments',body);const repeated=await request(buyer.cookie,'/simulated-payments',body);assert.equal(repeated.status,200);assert.equal(repeated.data.attempt.id,original.data.attempt.id);assert.equal(await prisma.simulatedPaymentAttempt.count({where:{transactionId:replayAgreement.id}}),1);pass('PAY-INT-08');
 const concurrent=await agreement(11);const race=await Promise.all([request(buyer.cookie,'/simulated-payments',input('APPROVED',randomUUID(),concurrent.id)),request(buyer.cookie,'/simulated-payments',input('APPROVED',randomUUID(),concurrent.id))]);assert.equal(race.filter(row=>row.status===201).length,1);assert.equal(race.filter(row=>row.status===409).length,1);assert.equal(await prisma.simulatedPaymentAttempt.count({where:{transactionId:concurrent.id,status:'APPROVED'}}),1);pass('PAY-INT-09');
 console.log(JSON.stringify({status:'passed',tests:results.length}));
}catch(error){const message=String((error as Error)?.message??'').replace(/https?:\/\/\S+/g,'[endpoint redacted]').replace(/postgres(?:ql)?:\/\/\S+/gi,'[database URL redacted]').replace(/[A-Za-z]:\\[^\r\n]+/g,'[local path redacted]').slice(0,240);console.log(JSON.stringify({status:'failed',passed:results.length,code:(error as any)?.code??'ASSERTION_OR_OPERATION_FAILED',phase,message}));process.exitCode=1;}
finally{try{const transactions=await prisma.energyTransaction.findMany({where:{sellerUserId:{in:users}},select:{id:true}});await prisma.$transaction(async tx=>{await tx.simulatedPaymentAttempt.deleteMany({where:{transactionId:{in:transactions.map(row=>row.id)}}});await tx.energyTransactionRevision.deleteMany({where:{transactionId:{in:transactions.map(row=>row.id)}}});await tx.energyTransaction.deleteMany({where:{sellerUserId:{in:users}}});await tx.publicationVerification.deleteMany({where:{userId:{in:users}}});await tx.simulationCapacityProfile.deleteMany({where:{userId:{in:users}}});await tx.energyOffer.deleteMany({where:{userId:{in:users}}});await tx.energyDemand.deleteMany({where:{userId:{in:users}}});await tx.energyPublication.deleteMany({where:{userId:{in:users}}});await tx.authSession.deleteMany({where:{userId:{in:users}}});await tx.user.deleteMany({where:{id:{in:users}}});},{timeout:30000});console.log(JSON.stringify({cleanup:'completed',fixturesOnly:true}));}catch{console.log(JSON.stringify({cleanup:'failed',runId}));process.exitCode=1;}server.close();await prisma.$disconnect();}
