import { describe, expect, test } from 'bun:test';
import express from 'express';
import { createEnergySeriesRouter } from '@/controllers/energy-series.controller';
import { createEnergySeriesService, type EnergySeriesStore } from '@/services/energy-series.service';

const day = (value: string) => new Date(`${value}T00:00:00Z`);
function records(metric: 'Gene' | 'DemaSIN' | 'PrecBolsNaci', from: string, count: number) {
  return Array.from({ length: count }, (_, dayIndex) => { const current = day(from); current.setUTCDate(current.getUTCDate() + dayIndex); const fecha_xm = current.toISOString().slice(0, 10);
    return metric === 'DemaSIN' ? [{ fecha_xm, demanda_kwh: 100 + dayIndex }] : Array.from({ length: 24 }, (_, index) => metric === 'Gene' ? { fecha_xm, hora_xm: index + 1, energia_kwh: index + 1 } : { fecha_xm, periodo: index + 1, precio_cop_kwh: index + 1 }); }).flat();
}
function source(metric: 'Gene' | 'DemaSIN' | 'PrecBolsNaci', from = '2024-01-01', count = 40) { const to = day(from); to.setUTCDate(to.getUTCDate() + count - 1); return { id: 9, metric, requestedFrom: day(from), requestedTo: to, contentHash: 'a'.repeat(64), energyDatasetId: 88, energyDataset: { content: { records: records(metric, from, count) } } }; }
function service(rows: ReturnType<typeof source>[]): ReturnType<typeof createEnergySeriesService> { const store: EnergySeriesStore = { findMany: async () => rows }; return createEnergySeriesService(store); }
async function request(app: express.Express, path: string) { const server = app.listen(0, '127.0.0.1'); await new Promise<void>(resolve => server.listening ? resolve() : server.once('listening', resolve)); const address = server.address(); if (!address || typeof address === 'string') throw Error('Expected listener'); try { const response = await fetch(`http://127.0.0.1:${address.port}${path}`); return { status: response.status, body: await response.json() as any }; } finally { server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve())); } }
function appFor(rows: ReturnType<typeof source>[], authenticated = true) { const app = express(); app.use('/energy-series', createEnergySeriesRouter(service(rows), authenticated ? (_req, _res, next) => next() : (_req, res) => res.status(401).json({ error: 'UNAUTHENTICATED' }))); return app; }

describe('GET /energy-series', () => {
  test('devuelve Gene hourly ordenado, con períodos y trazabilidad canónica', async () => { const response = await request(appFor([source('Gene')]), '/energy-series?metric=gene&from=2024-01-01&to=2024-01-02&granularity=hourly'); expect(response.status).toBe(200); expect(response.body).toMatchObject({ metric: 'gene', unit: 'kWh', pointCount: 48, sourceDatasetId: 88, consolidatedDatasetId: 9, coverage: { availableFrom: '2024-01-01', availableUntil: '2024-02-09' } }); expect(response.body.points[0]).toEqual({ date: '2024-01-01', period: 1, value: 1 }); expect(response.body.points.at(-1)).toEqual({ date: '2024-01-02', period: 24, value: 24 }); expect(typeof response.body.points[0].value).toBe('number'); });
  test('agrega Gene diario por suma y mensual por suma', async () => { const app = appFor([source('Gene')]); const daily = await request(app, '/energy-series?metric=gene&from=2024-01-01&to=2024-01-02&granularity=daily'); const monthly = await request(app, '/energy-series?metric=gene&from=2024-01-01&to=2024-02-09&granularity=monthly'); expect(daily.body.points).toEqual([{ date: '2024-01-01', value: 300 }, { date: '2024-01-02', value: 300 }]); expect(monthly.body.points).toEqual([{ date: '2024-01', value: 9300 }, { date: '2024-02', value: 2700 }]); });
  test('devuelve DemaSIN daily y monthly sin horas inventadas', async () => { const app = appFor([source('DemaSIN')]); const daily = await request(app, '/energy-series?metric=demand&from=2024-01-01&to=2024-01-02&granularity=daily'); const monthly = await request(app, '/energy-series?metric=demand&from=2024-01-01&to=2024-02-09&granularity=monthly'); expect(daily.body).toMatchObject({ unit: 'kWh', points: [{ date: '2024-01-01', value: 100 }, { date: '2024-01-02', value: 101 }] }); expect(JSON.stringify(daily.body.points)).not.toContain('period'); expect(monthly.body.points).toEqual([{ date: '2024-01', value: 3565 }, { date: '2024-02', value: 1215 }]); });
  test('devuelve Precio hourly y agrega diario/mensual por promedio numérico', async () => { const app = appFor([source('PrecBolsNaci')]); const hourly = await request(app, '/energy-series?metric=price&from=2024-01-01&to=2024-01-01&granularity=hourly'); const daily = await request(app, '/energy-series?metric=price&from=2024-01-01&to=2024-01-01&granularity=daily'); const monthly = await request(app, '/energy-series?metric=price&from=2024-01-01&to=2024-02-09&granularity=monthly'); expect(hourly.body).toMatchObject({ unit: 'COP/kWh', pointCount: 24 }); expect(typeof hourly.body.points[0].value).toBe('number'); expect(daily.body.points).toEqual([{ date: '2024-01-01', value: 12.5 }]); expect(monthly.body.points).toEqual([{ date: '2024-01', value: 12.5 }, { date: '2024-02', value: 12.5 }]); });
  test('rechaza autenticación, métrica, granularidad, rango y cobertura inválidos', async () => { expect((await request(appFor([source('Gene')], false), '/energy-series?metric=gene&from=2024-01-01&to=2024-01-01&granularity=hourly')).status).toBe(401); const app = appFor([source('Gene')]); for (const path of ['/energy-series?metric=other&from=2024-01-01&to=2024-01-01&granularity=hourly', '/energy-series?metric=demand&from=2024-01-01&to=2024-01-01&granularity=hourly', '/energy-series?metric=gene&from=2024-02-01&to=2024-01-01&granularity=hourly']) expect((await request(app, path)).status).toBe(400); expect((await request(app, '/energy-series?metric=gene&from=2024-01-01&to=2024-02-01&granularity=hourly')).status).toBe(413); expect(await request(app, '/energy-series?metric=gene&from=2025-01-01&to=2025-01-01&granularity=daily')).toMatchObject({ status: 404, body: { error: 'ENERGY_SERIES_UNAVAILABLE' } }); });
  test('protege el error inesperado del servicio', async () => { const app = express(); app.use('/energy-series', createEnergySeriesRouter({ read: async () => { throw Error('DATABASE_URL secret'); } } as any, (_req, _res, next) => next(), { error: () => undefined })); const response = await request(app, '/energy-series?metric=gene&from=2024-01-01&to=2024-01-01&granularity=hourly'); expect(response).toEqual({ status: 500, body: { error: 'ENERGY_SERIES_FAILED', message: 'No fue posible consultar las series históricas.' } }); });
});