import {test,expect,mock,afterAll} from 'bun:test';
import express from 'express';
import {request} from 'node:http';
import {readFileSync} from 'node:fs';
import evaluation from '@/models/xm-gene-ridge/1.0.0/evaluation.json';
import {loadModel} from '@/models/xm-gene-ridge/model-loader';
import {validateEvaluation,createEvaluationLoader,loadEvaluation} from '@/models/xm-gene-ridge/evaluation-loader';
import {getForecastMetrics} from '@/services/forecast-metrics.service';
const forbidden=mock(()=>{throw Error('unexpected database call');});
mock.module('@/lib/prisma',()=>({prisma:{preparedDataset:{findUnique:forbidden,create:forbidden},energyDataset:{findUnique:forbidden,create:forbidden,updateMany:forbidden}}}));
const {createForecastRouter}=await import('@/controllers/forecast.controller');
const app=express();app.use('/forecasts',createForecastRouter());
app.use('/broken',createForecastRouter(undefined,()=>{createEvaluationLoader(()=>{throw Error('private path');})();return getForecastMetrics();}));
app.use('/unexpected',createForecastRouter(undefined,()=>{throw Error('secret');}));
const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.listening?r():server.once('listening',r));
const address=server.address();if(!address||typeof address==='string')throw Error('listener');const base=`http://127.0.0.1:${address.port}`;
afterAll(()=>new Promise<void>(r=>server.close(()=>r())));
test('HU05 HTTP exact contract and identity shared with active model',async()=>{
 const r=await fetch(base+'/forecasts/supply/metrics');expect(r.status).toBe(200);const body=await r.json();const m=loadModel();
 expect(body).toEqual({status:'available',modelId:m.modelId,modelVersion:m.modelVersion,active:true,forecastType:'generation_availability_proxy',target:'energia_kwh',unit:'kWh',horizonPeriods:24,training:{trainedAt:null,trainedAtStatus:'not_recorded',snapshotSha256:m.trainingSnapshotSha256,sourceRange:m.trainingSourceRange,effectiveRange:m.effectiveTrainingRange},evaluation:{type:'external_temporal_holdout',range:evaluation.evaluationRange,snapshotSha256:evaluation.evaluationSnapshotSha256,evaluable:720,unavailable:0,MAE:{value:329144.1790612068,unit:'kWh'},RMSE:{value:438880.23646857974,unit:'kWh'},bias:{value:-17643.615971800806,unit:'kWh'},percentageError:{metric:'WAPE',value:3.4778347681971216,unit:'percent'}}});expect(forbidden).not.toHaveBeenCalled();
});
test('no query selection',async()=>expect((await fetch(base+'/forecasts/supply/metrics?modelVersion=2')).status).toBe(400));
test('GET body rejected',async()=>{const status=await new Promise<number>(resolve=>{const req=request(base+'/forecasts/supply/metrics',{method:'GET',headers:{'Content-Length':2}},res=>{res.resume();resolve(res.statusCode!);});req.end('{}');});expect(status).toBe(400);});
test('safe missing evaluation and unexpected failure',async()=>{let r=await fetch(base+'/broken/supply/metrics');expect(r.status).toBe(409);expect(await r.json()).toEqual({status:'unavailable',error:'FORECAST_MODEL_INCOMPATIBLE',message:'El modelo de pronóstico no está disponible o no es compatible.'});r=await fetch(base+'/unexpected/supply/metrics');expect(r.status).toBe(500);expect(await r.text()).not.toContain('secret');});
test('loader cached and frozen',()=>{const read=mock(()=>JSON.stringify(evaluation));const loader=createEvaluationLoader(read);expect(loader()).toBe(loader());expect(read).toHaveBeenCalledTimes(1);expect(Object.isFrozen(loadEvaluation().metrics.WAPE)).toBe(true);});
test.each(['modelId','modelVersion','trainingSnapshotSha256','evaluationSnapshotSha256','evaluationRange','evaluable','unavailable','trainedAt','trainedAtStatus'])('invalid %s',key=>{const e:any=structuredClone(evaluation);e[key]=key==='trainedAt'?'2024-01-01':null;expect(()=>validateEvaluation(e,loadModel())).toThrow();});
test.each(['MAE','RMSE','bias','WAPE'])('nonfinite %s',key=>{for(const value of [NaN,Infinity]){const e=structuredClone(evaluation);e.metrics[key as keyof typeof e.metrics].value=value;expect(()=>validateEvaluation(e,loadModel())).toThrow();}});
test.each([0,-1,Infinity])('bad denominator %s',value=>{const e=structuredClone(evaluation);e.metrics.WAPE.denominatorAbsoluteActualKwh=value;expect(()=>validateEvaluation(e,loadModel())).toThrow();});
test('bad numerator, unit and mismatched recorded metric',()=>{for(const change of [(e:any)=>e.metrics.WAPE.numeratorAbsoluteErrorKwh=-1,(e:any)=>e.metrics.MAE.unit='percent',(e:any)=>e.metrics.MAE.value=1]){const e=structuredClone(evaluation);change(e);expect(()=>validateEvaluation(e,loadModel())).toThrow();}});
test('invalid JSON and missing model fail closed',()=>{expect(()=>createEvaluationLoader(()=>'{')()).toThrow();expect(()=>createEvaluationLoader(()=>JSON.stringify(evaluation),()=>{throw Error('missing');})()).toThrow();});
test('metrics dependencies exclude database, XM and training',()=>{const s=readFileSync(new URL('../services/forecast-metrics.service.ts',import.meta.url),'utf8');expect(s).not.toMatch(/prisma|fetch\s*\(|XmProvider|prepareDataset|\bfit\s*\(/);});
