import { useEffect, useEffectEvent, useRef, useState, type FormEvent } from 'react'
import { LocalizedDecimalInput } from '../components/forms/LocalizedDecimalInput'
import { DataTable } from '../components/tables/DataTable'
import { SectionHeader } from '../components/ui/SectionHeader'
import { StatusBadge } from '../components/ui/StatusBadge'
import { MatchingResults, type MatchingPresentationState } from '../components/matching/MatchingResults'
import { useVisiblePolling } from '../hooks/useVisiblePolling'
import { cancelDemand, cancelOffer, createDemand, createOffer, getMyDemands, getMyOffers, listMarketDemands, listMarketOffers, updateDemand, updateOffer } from '../services/marketplaceService'
import { suggestMatches } from '../services/matchingService'
import { createTransaction } from '../services/transactionService'
import type { EnergyDemandDto, EnergyMarketStatus, EnergyOfferDto, MarketDemand, MarketOffer } from '../types/marketplace'
import type { EnergyTransaction } from '../types/transactions'
import { errorMessage, selectProposal, type SelectedProposal } from '../utils/marketplaceActions'
import { filteredPublications, marketFingerprint, publicationEmptyLabel, publicationFilters } from '../utils/marketplaceSync'
import { formatCopPerKwh, formatDeliveryDate, formatEnergy, formatEnergyKWh } from '../utils/numberFormat'
import { parseLocalizedDecimal } from '../utils/localizedDecimal'
import './Marketplace.css'

const positive = (value: string, mode: 'quantity' | 'price') => {
  const parsed = parseLocalizedDecimal(value, mode).numberValue
  return parsed !== null && parsed > 0 ? parsed : null
}

type MatchingState = MatchingPresentationState

export function CompatibilityAction({ ownOffer, ownDemand, externalOffer, externalDemand, onSelect }: { ownOffer?: EnergyOfferDto; ownDemand?: EnergyDemandDto; externalOffer?: MarketOffer; externalDemand?: MarketDemand; onSelect: () => void }) {
  const own = ownOffer ?? ownDemand!
  const external = externalOffer ?? externalDemand!
  const negotiableQuantity = Math.min(own.quantityKwh, Number(external.availableQuantityKwh))
  const quantityCompatible = negotiableQuantity > 0
  const dateCompatible = own.deliveryDate === external.deliveryDate
  const priceCompatible = ownOffer ? ownOffer.pricePerKwh <= Number(externalDemand!.maxPricePerKwh) : ownDemand!.maxPricePerKwh >= Number(externalOffer!.pricePerKwh)
  const negotiable = quantityCompatible && dateCompatible
  const blockingMessage = !dateCompatible ? 'La negociación no está disponible porque las fechas de entrega no coinciden.' : !quantityCompatible ? 'La negociación no está disponible porque no hay saldo disponible.' : null
  return <div className="marketplace-compatibility"><strong>{ownOffer ? 'Tu oferta' : 'Tu demanda'}: {quantityCompatible ? `Cantidad negociable hasta ${formatEnergyKWh(negotiableQuantity)}.` : 'sin cantidad negociable'}, {dateCompatible ? 'fecha compatible' : 'fecha no compatible'}, {priceCompatible ? 'precio compatible' : 'precio no compatible'}.</strong>{!priceCompatible && <span className="marketplace-incompatibility">El precio no cumple el criterio de matching automático, pero puedes iniciar una negociación.</span>}{blockingMessage && <span className="marketplace-incompatibility">{blockingMessage}</span>}<button className={`secondary-button${negotiable ? '' : ' marketplace-disabled-action'}`} type="button" disabled={!negotiable} aria-disabled={!negotiable} title={blockingMessage ?? undefined} onClick={onSelect}>{ownOffer ? 'Negociar con mi oferta' : 'Negociar con mi demanda'}</button></div>
}

export function ActiveMarket({ offers, demands, ownOffers, ownDemands, onRefresh, onNavigate }: { offers: MarketOffer[]; demands: MarketDemand[]; ownOffers: EnergyOfferDto[]; ownDemands: EnergyDemandDto[]; onRefresh: () => void; onNavigate?: () => void }) {
  const [selected, setSelected] = useState<SelectedProposal | null>(null)
  const [created, setCreated] = useState<EnergyTransaction | null>(null)
  const [quantity, setQuantity] = useState('')
  const [price, setPrice] = useState('')
  const [error, setError] = useState('')
  const [status, setStatus] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const selectedHeading = useRef<HTMLHeadingElement>(null)
  useEffect(() => { selectedHeading.current?.focus() }, [selected])
  const availableOwnOffers = ownOffers.map(offer => ({ ...offer, quantityKwh: offer.availableQuantityKwh })).filter(offer => offer.status === 'ACTIVE' && offer.quantityKwh > 0)
  const availableOwnDemands = ownDemands.map(demand => ({ ...demand, quantityKwh: demand.availableQuantityKwh })).filter(demand => demand.status === 'ACTIVE' && demand.quantityKwh > 0)
  const select = (offer: MarketOffer, demand: EnergyDemandDto, initialPrice: number) => { const proposal = selectProposal(offer, demand); setSelected(proposal); setQuantity(String(proposal.max)); setPrice(String(initialPrice)); setCreated(null); setError(''); setStatus('') }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const amount = positive(quantity, 'quantity')
    const proposedPrice = positive(price, 'price')
    if (!selected || amount === null || amount > selected.max) { setError('Ingresa una cantidad válida mayor que cero.'); return }
    if (proposedPrice === null) { setError('Ingresa un precio válido mayor que cero.'); return }
    setSubmitting(true); setError('')
    try {
      const transaction = await createTransaction({ offerId: selected.offer.id, demandId: selected.demand.id, quantityKwh: amount, pricePerKwh: proposedPrice })
      setCreated(transaction); setStatus('Tu propuesta fue registrada. La contraparte puede aceptarla, rechazarla o contrapropor.'); setSelected(null); onRefresh()
    } catch (reason) { setError(errorMessage(reason)) } finally { setSubmitting(false) }
  }
  return <section className="panel marketplace-section" aria-label="Mercado activo"><SectionHeader eyebrow="Mercado activo" title="Publicaciones disponibles" description="Saldos de publicaciones activas de otros usuarios. Las sugerencias de matching siguen siendo informativas." />
    {status && <p className="marketplace-status" role="status">{status}</p>}{error && <p className="marketplace-error" role="alert">{error}</p>}
    {created && <section className="proposal-result" aria-label="Propuesta creada"><strong>Estado: Pendiente</strong><span>Cantidad: {formatEnergyKWh(Number(created.quantityKwh))}</span><span>Precio: {formatCopPerKwh(Number(created.pricePerKwh))}</span><span>Total: {new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP' }).format(Number(created.totalAmountCop))}</span><span>Entrega: {formatDeliveryDate(created.deliveryDate)}</span>{onNavigate && <button type="button" className="primary-button" onClick={onNavigate}>Ver mis transacciones</button>}</section>}
    {selected && <section className="proposal-selected" aria-label="Propuesta seleccionada"><h3 ref={selectedHeading} tabIndex={-1}>Propuesta seleccionada</h3><div className="proposal-details"><p><strong>Oferta:</strong> {formatEnergyKWh(Number(selected.offer.availableQuantityKwh))} a {formatCopPerKwh(Number(selected.offer.pricePerKwh))}. Entrega: {formatDeliveryDate(selected.offer.deliveryDate)}.</p><p><strong>Demanda:</strong> {formatEnergy(selected.demand.quantityKwh)}. Máximo: {formatCopPerKwh(selected.demand.maxPricePerKwh)}. Entrega: {formatDeliveryDate(selected.demand.deliveryDate)}.</p><p><strong>Cantidad máxima:</strong> {formatEnergyKWh(selected.max)}</p></div><form className="marketplace-form" onSubmit={submit}><label>Cantidad a transaccionar (kWh)<LocalizedDecimalInput mode="quantity" value={quantity} onValueChange={value => setQuantity(value.displayValue)} disabled={submitting} required /></label><label>Precio propuesto (COP/kWh)<LocalizedDecimalInput mode="price" value={price} onValueChange={value => setPrice(value.displayValue)} disabled={submitting} required /></label><div className="marketplace-actions"><button className="primary-button" disabled={submitting}>{submitting ? 'Creando…' : 'Crear negociación'}</button><button type="button" className="secondary-button" onClick={() => setSelected(null)} disabled={submitting}>Cancelar</button></div></form></section>}
    <div className="marketplace-columns"><div><h3>Ofertas activas</h3>{offers.length === 0 ? <p className="marketplace-empty">No hay ofertas externas disponibles.</p> : <div className="marketplace-list">{offers.map(offer => <article className="marketplace-item" key={offer.id}><strong>{formatEnergyKWh(Number(offer.availableQuantityKwh))} disponibles</strong><span>{formatCopPerKwh(Number(offer.pricePerKwh))}</span><span>Entrega: {formatDeliveryDate(offer.deliveryDate)}</span>{availableOwnDemands.map(demand => <CompatibilityAction key={demand.id} ownDemand={demand} externalOffer={offer} onSelect={() => select(offer, demand, demand.maxPricePerKwh)} />)}</article>)}</div>}</div><div><h3>Demandas activas</h3>{demands.length === 0 ? <p className="marketplace-empty">No hay demandas externas disponibles.</p> : <div className="marketplace-list">{demands.map(demand => <article className="marketplace-item" key={demand.id}><strong>{formatEnergyKWh(Number(demand.availableQuantityKwh))} pendientes</strong><span>Máximo: {formatCopPerKwh(Number(demand.maxPricePerKwh))}</span><span>Entrega: {formatDeliveryDate(demand.deliveryDate)}</span>{availableOwnOffers.map(offer => <CompatibilityAction key={offer.id} ownOffer={offer} externalDemand={demand} onSelect={() => select({ id: offer.id, availableQuantityKwh: String(offer.quantityKwh), pricePerKwh: String(offer.pricePerKwh), deliveryDate: offer.deliveryDate, status: 'ACTIVE' }, { id: demand.id, quantityKwh: Number(demand.availableQuantityKwh), confirmedQuantityKwh: 0, reservedQuantityKwh: 0, availableQuantityKwh: Number(demand.availableQuantityKwh), maxPricePerKwh: Number(demand.maxPricePerKwh), deliveryDate: demand.deliveryDate, status: 'ACTIVE', createdAt: '', updatedAt: '' }, offer.pricePerKwh)} />)}</article>)}</div>}</div></div>
  </section>
}

function OfferForm({ onCreated }: { onCreated: (offer: EnergyOfferDto) => void }) {
  const [quantity, setQuantity] = useState(''); const [price, setPrice] = useState(''); const [deliveryDate, setDeliveryDate] = useState(''); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const [confirmation, setConfirmation] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const quantityKwh = positive(quantity, 'quantity'); const pricePerKwh = positive(price, 'price'); if (quantityKwh === null) { setError('Ingresa una cantidad válida mayor que cero.'); return } if (pricePerKwh === null || !deliveryDate) { setError(pricePerKwh === null ? 'Ingresa un precio válido mayor que cero.' : 'Ingresa una fecha de entrega válida.'); return } setSubmitting(true); setError(''); try { onCreated(await createOffer({ quantityKwh, pricePerKwh, deliveryDate })); setQuantity(''); setPrice(''); setDeliveryDate(''); setConfirmation('Oferta publicada correctamente.') } catch (reason) { setError(errorMessage(reason)) } finally { setSubmitting(false) } }
  return <form className="marketplace-form" onSubmit={submit} aria-busy={submitting}><label>Cantidad de energía (kWh)<LocalizedDecimalInput mode="quantity" value={quantity} onValueChange={value => setQuantity(value.displayValue)} disabled={submitting} required /></label><label>Precio (COP/kWh)<LocalizedDecimalInput mode="price" value={price} onValueChange={value => setPrice(value.displayValue)} disabled={submitting} required /></label><label>Fecha de entrega<input type="date" value={deliveryDate} onChange={event => setDeliveryDate(event.target.value)} required disabled={submitting} /></label>{error && <p className="marketplace-error" role="alert">{error}</p>}{confirmation && <p className="marketplace-status" role="status">{confirmation}</p>}<button type="submit" className="primary-button" disabled={submitting}>{submitting ? 'Publicando…' : 'Publicar oferta'}</button></form>
}

function DemandForm({ onCreated }: { onCreated: (demand: EnergyDemandDto) => void }) {
  const [quantity, setQuantity] = useState(''); const [price, setPrice] = useState(''); const [deliveryDate, setDeliveryDate] = useState(''); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const [confirmation, setConfirmation] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const quantityKwh = positive(quantity, 'quantity'); const maxPricePerKwh = positive(price, 'price'); if (quantityKwh === null) { setError('Ingresa una cantidad válida mayor que cero.'); return } if (maxPricePerKwh === null || !deliveryDate) { setError(maxPricePerKwh === null ? 'Ingresa un precio válido mayor que cero.' : 'Ingresa una fecha de entrega válida.'); return } setSubmitting(true); setError(''); try { onCreated(await createDemand({ quantityKwh, maxPricePerKwh, deliveryDate })); setQuantity(''); setPrice(''); setDeliveryDate(''); setConfirmation('Demanda publicada correctamente.') } catch (reason) { setError(errorMessage(reason)) } finally { setSubmitting(false) } }
  return <form className="marketplace-form" onSubmit={submit} aria-busy={submitting}><label>Cantidad de energía (kWh)<LocalizedDecimalInput mode="quantity" value={quantity} onValueChange={value => setQuantity(value.displayValue)} disabled={submitting} required /></label><label>Precio máximo (COP/kWh)<LocalizedDecimalInput mode="price" value={price} onValueChange={value => setPrice(value.displayValue)} disabled={submitting} required /></label><label>Fecha de entrega<input type="date" value={deliveryDate} onChange={event => setDeliveryDate(event.target.value)} required disabled={submitting} /></label>{error && <p className="marketplace-error" role="alert">{error}</p>}{confirmation && <p className="marketplace-status" role="status">{confirmation}</p>}<button type="submit" className="primary-button" disabled={submitting}>{submitting ? 'Publicando…' : 'Publicar demanda'}</button></form>
}

export function PublicationActions({ type, publication, onChanged }: { type: 'offer' | 'demand'; publication: EnergyOfferDto | EnergyDemandDto; onChanged: (value: EnergyOfferDto | EnergyDemandDto) => void }) {
  const [editing, setEditing] = useState(false); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const [quantity, setQuantity] = useState(''); const [price, setPrice] = useState(''); const [deliveryDate, setDeliveryDate] = useState('')
  if (publication.status !== 'ACTIVE') return null
  function startEdit() { setQuantity(String(publication.quantityKwh)); setPrice(String(type === 'offer' ? (publication as EnergyOfferDto).pricePerKwh : (publication as EnergyDemandDto).maxPricePerKwh)); setDeliveryDate(publication.deliveryDate); setEditing(true) }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const quantityKwh = positive(quantity, 'quantity'); const parsedPrice = positive(price, 'price'); if (quantityKwh === null) { setError('Ingresa una cantidad válida mayor que cero.'); return } if (parsedPrice === null || !deliveryDate) { setError(parsedPrice === null ? 'Ingresa un precio válido mayor que cero.' : 'Ingresa una fecha de entrega válida.'); return } setSubmitting(true); setError(''); try { const updated = type === 'offer' ? await updateOffer(publication.id, { quantityKwh, pricePerKwh: parsedPrice, deliveryDate }) : await updateDemand(publication.id, { quantityKwh, maxPricePerKwh: parsedPrice, deliveryDate }); onChanged(updated); setEditing(false) } catch (reason) { setError(errorMessage(reason)) } finally { setSubmitting(false) } }
  async function cancel() { if (!window.confirm('Esta publicación dejará de estar disponible en el mercado.')) return; setSubmitting(true); setError(''); try { onChanged(type === 'offer' ? await cancelOffer(publication.id) : await cancelDemand(publication.id)) } catch (reason) { setError(errorMessage(reason)) } finally { setSubmitting(false) } }
  if (!editing) return <div className="marketplace-actions publication-actions"><button className="secondary-button publication-action-button" type="button" onClick={startEdit} disabled={submitting}>Editar</button><button className="secondary-button publication-action-button" type="button" onClick={() => { void cancel() }} disabled={submitting}>Cancelar</button>{error && <p className="marketplace-error" role="alert">{error}</p>}</div>
  return <form className="marketplace-form" onSubmit={save}><label>Cantidad<LocalizedDecimalInput mode="quantity" value={quantity} onValueChange={value => setQuantity(value.displayValue)} disabled={submitting} required /></label><label>{type === 'offer' ? 'Precio (COP/kWh)' : 'Precio máximo (COP/kWh)'}<LocalizedDecimalInput mode="price" value={price} onValueChange={value => setPrice(value.displayValue)} disabled={submitting} required /></label><label>Entrega<input type="date" value={deliveryDate} onChange={event => setDeliveryDate(event.target.value)} disabled={submitting} required /></label>{error && <p className="marketplace-error" role="alert">{error}</p>}<div className="marketplace-actions"><button className="primary-button" disabled={submitting}>{submitting ? 'Guardando…' : 'Guardar cambios'}</button><button className="secondary-button" type="button" onClick={() => setEditing(false)} disabled={submitting}>Cancelar edición</button></div></form>
}

export function PublicationStatus({ status }: { status: EnergyOfferDto['status'] }) { return <StatusBadge tone={status === 'FULFILLED' || status === 'ACTIVE' ? 'success' : status === 'EXPIRED' ? 'warning' : 'neutral'}>{status === 'FULFILLED' ? 'Completada' : status === 'CANCELLED' ? 'Cancelada' : status === 'EXPIRED' ? 'Vencida' : 'Activa'}</StatusBadge> }
export function PublicationQuantity({ type, publication }: { type: 'offer' | 'demand'; publication: EnergyOfferDto | EnergyDemandDto }) { const availableLabel = type === 'offer' ? 'disponibles' : 'pendientes'; const originalLabel = type === 'offer' ? 'Publicada' : 'Solicitada'; return <div className="publication-quantity"><strong>{formatEnergyKWh(publication.availableQuantityKwh)} {availableLabel}</strong><span>{originalLabel}: {formatEnergyKWh(publication.quantityKwh)}</span><span>Confirmada: {formatEnergyKWh(publication.confirmedQuantityKwh)}</span>{publication.reservedQuantityKwh > 0 && <span>Reservada: {formatEnergyKWh(publication.reservedQuantityKwh)}</span>}</div> }
function offerColumns(onChanged: (value: EnergyOfferDto) => void) { return [{ header: 'Disponible', render: (row: EnergyOfferDto) => <PublicationQuantity type="offer" publication={row} /> }, { header: 'Precio', render: (row: EnergyOfferDto) => formatCopPerKwh(row.pricePerKwh) }, { header: 'Fecha de entrega', render: (row: EnergyOfferDto) => formatDeliveryDate(row.deliveryDate) }, { header: 'Estado', render: (row: EnergyOfferDto) => <PublicationStatus status={row.status} /> }, { header: 'Acciones', className: 'publication-actions-cell', render: (row: EnergyOfferDto) => <PublicationActions type="offer" publication={row} onChanged={value => onChanged(value as EnergyOfferDto)} /> }] }
function demandColumns(onChanged: (value: EnergyDemandDto) => void) { return [{ header: 'Pendiente', render: (row: EnergyDemandDto) => <PublicationQuantity type="demand" publication={row} /> }, { header: 'Precio máximo', render: (row: EnergyDemandDto) => formatCopPerKwh(row.maxPricePerKwh) }, { header: 'Fecha de entrega', render: (row: EnergyDemandDto) => formatDeliveryDate(row.deliveryDate) }, { header: 'Estado', render: (row: EnergyDemandDto) => <PublicationStatus status={row.status} /> }, { header: 'Acciones', className: 'publication-actions-cell', render: (row: EnergyDemandDto) => <PublicationActions type="demand" publication={row} onChanged={value => onChanged(value as EnergyDemandDto)} /> }] }

export function MatchingContent({ state, stale = false, onSuggest }: { state: MatchingState; stale?: boolean; onSuggest: () => void }) { return <MatchingResults state={state} stale={stale} onSuggest={onSuggest} /> }

function PublicationFilter({ value, counts, onChange }: { value: EnergyMarketStatus | 'ALL'; counts: Record<EnergyMarketStatus | 'ALL', number>; onChange: (value: EnergyMarketStatus | 'ALL') => void }) { return <div className="publication-filters">{publicationFilters.map(filter => <button key={filter.value} type="button" className={value === filter.value ? 'primary-button' : 'secondary-button'} onClick={() => onChange(filter.value)}>{filter.label} ({counts[filter.value]})</button>)}</div> }
function counts<T extends EnergyOfferDto | EnergyDemandDto>(publications: T[]) { return Object.fromEntries(publicationFilters.map(filter => [filter.value, filter.value === 'ALL' ? publications.length : publications.filter(publication => publication.status === filter.value).length])) as Record<EnergyMarketStatus | 'ALL', number> }

export function Marketplace({ onNavigate }: { onNavigate?: () => void }) {
  const [offers, setOffers] = useState<EnergyOfferDto[]>([]); const [demands, setDemands] = useState<EnergyDemandDto[]>([]); const [marketOffers, setMarketOffers] = useState<MarketOffer[]>([]); const [marketDemands, setMarketDemands] = useState<MarketDemand[]>([]); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(''); const [matching, setMatching] = useState<MatchingState>({ kind: 'idle' }); const [matchingStale, setMatchingStale] = useState(false); const [offerFilter, setOfferFilter] = useState<EnergyMarketStatus | 'ALL'>('ACTIVE'); const [demandFilter, setDemandFilter] = useState<EnergyMarketStatus | 'ALL'>('ACTIVE'); const [currentFingerprint, setCurrentFingerprint] = useState(''); const [matchingFingerprint, setMatchingFingerprint] = useState<string | null>(null)
  const refreshMarket = (signal?: AbortSignal) => {
    const work = Promise.all([getMyOffers(signal), getMyDemands(signal), listMarketOffers(signal), listMarketDemands(signal)]).then(([loadedOffers, loadedDemands, loadedMarketOffers, loadedMarketDemands]) => {
      if (signal?.aborted) return
      const fingerprint = marketFingerprint(loadedMarketOffers, loadedMarketDemands)
      if (matchingFingerprint !== null && matchingFingerprint !== fingerprint) setMatchingStale(true)
      setCurrentFingerprint(fingerprint); setOffers(loadedOffers); setDemands(loadedDemands); setMarketOffers(loadedMarketOffers); setMarketDemands(loadedMarketDemands); setLoadError('')
    }).catch(reason => { if (!signal?.aborted) setLoadError(errorMessage(reason)) })
    return work
  }
  const refreshInitially = useEffectEvent((signal: AbortSignal) => refreshMarket(signal))
  useEffect(() => { const controller = new AbortController(); void refreshInitially(controller.signal).finally(() => { if (!controller.signal.aborted) setLoading(false) }); return () => controller.abort() }, [])
  useVisiblePolling(signal => refreshMarket(signal), 5000, true)
  async function suggest() { if (matching.kind === 'loading') return; setMatching({ kind: 'loading', message: 'Generando sugerencias…' }); try { setMatching({ kind: 'success', result: await suggestMatches() }); setMatchingFingerprint(currentFingerprint); setMatchingStale(false) } catch (reason) { setMatching({ kind: 'error', message: errorMessage(reason) }) } }
  const immediateRefresh = () => { void refreshMarket() }
  const replaceOffer = (offer: EnergyOfferDto) => { setOffers(current => current.map(value => value.id === offer.id ? offer : value)); immediateRefresh() }
  const replaceDemand = (demand: EnergyDemandDto) => { setDemands(current => current.map(value => value.id === demand.id ? demand : value)); immediateRefresh() }
  const visibleOffers = filteredPublications(offers, offerFilter); const visibleDemands = filteredPublications(demands, demandFilter)
  return <div className="page-grid marketplace-page"><section className="panel marketplace-intro"><SectionHeader eyebrow="Mercado energético" title="Mercado energético simulado" description="Publica energía propia, consulta saldos externos y crea propuestas de intercambio simulado." /></section><MatchingContent state={matching} stale={matchingStale} onSuggest={() => { void suggest() }} />{loading && <p role="status">Cargando tus publicaciones…</p>}{loadError && <div className="panel" role="alert"><p className="marketplace-error">{loadError}</p><button type="button" className="secondary-button" onClick={() => { setLoading(true); void refreshMarket().finally(() => setLoading(false)) }}>Reintentar carga</button></div>}{!loading && !loadError && <div className="marketplace-columns"><section className="panel marketplace-section" aria-label="Ofertas"><SectionHeader eyebrow="Publicación" title="Ofertas" description="Energía que deseas poner a disposición." /><OfferForm onCreated={offer => { setOffers(current => [offer, ...current]); immediateRefresh() }} /><PublicationFilter value={offerFilter} counts={counts(offers)} onChange={setOfferFilter} />{visibleOffers.length === 0 ? <p className="marketplace-empty">{publicationEmptyLabel('ofertas', offerFilter)}</p> : <DataTable columns={offerColumns(replaceOffer)} rows={visibleOffers} getRowKey={row => row.id} />}</section><section className="panel marketplace-section" aria-label="Demandas"><SectionHeader eyebrow="Publicación" title="Demandas" description="Energía que deseas adquirir." /><DemandForm onCreated={demand => { setDemands(current => [demand, ...current]); immediateRefresh() }} /><PublicationFilter value={demandFilter} counts={counts(demands)} onChange={setDemandFilter} />{visibleDemands.length === 0 ? <p className="marketplace-empty">{publicationEmptyLabel('demandas', demandFilter)}</p> : <DataTable columns={demandColumns(replaceDemand)} rows={visibleDemands} getRowKey={row => row.id} />}</section></div>}{!loading && !loadError && <ActiveMarket offers={marketOffers} demands={marketDemands} ownOffers={offers} ownDemands={demands} onRefresh={immediateRefresh} onNavigate={onNavigate} />}</div>
}
